// src/renderer/pages/general/lists/components/mods-popup.vue
<template>
  <Modal
    :title="items ? texts.modsPopupTitle : texts.loading"
    :open="show"
    :ok-text="texts.ok"
    :cancel-text="texts.cancel"
    @ok="saveChanges"
    @cancel="hidePopup"
  >
    <template v-if="items">
      <Transfer
        class="mods-transfer"
        :data-source="items.map(([file, name]) => ({
          key: file.path,
          title: name
        }))"
        :target-keys="targetKeys"
        :titles="[texts.foundItems, texts.addedItems]"
        :render="item => item.title"
        :locale="transferLocale"
        @change="newKeys => targetKeys = newKeys"
      />
      <Button
        class="mods-manual-button"
        @click="async () => addItems(await Mods.request())"
      >
        {{ texts.manualMod }}
      </Button>
      <Button
        class="mods-manual-button"
        @click="async () => addItems(await Mods.requestDirs())"
      >
        {{ texts.manualModFolder }}
      </Button>
    </template>
    <Spin v-else />
  </Modal>
</template>

<script lang='ts' setup>
import type { ModalProps, TransferProps } from 'ant-design-vue'
import { Button, Modal, Transfer } from 'ant-design-vue'
import { ref, watchEffect } from 'vue'
import texts from '../texts'
import type { File } from '/mods/renderer'
import { Mods } from '/mods/renderer'
import { Spin } from '/rend/components'
import type { EmitsToProps } from '/rend/types'

export type ModsPopupProps = Props & EmitsToProps<Emits>
  
type Props = {
  show: boolean
}
type Emits = {
  hide: [reload: boolean]
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const items = ref<[File, string][] | undefined>(undefined)
const targetKeys = ref<string[]>([])

const transferLocale: TransferProps['locale'] = {
  itemUnit: '',
  itemsUnit: '',
  searchPlaceholder: '',
  notFoundContent: texts.emptyList
}

watchEffect(async () => {
  if (!props.show || items.value) {
    return
  }
    
  const loaded = await Mods.getAllMods()

  items.value = loaded
  targetKeys.value = getTargetKeys(loaded)
})

const saveChanges: ModalProps['onOk'] = () => {
  if (!items.value) {
    return
  }

  Mods.saveFromSelect(targetKeys.value, items.value)
  emit('hide', true)
}

const hidePopup: ModalProps['onCancel'] = () => {
  if (!items.value) {
    return
  }
  
  targetKeys.value = getTargetKeys(items.value)
  emit('hide', false)
}

function getTargetKeys(items: [File, string][]): string[] {
  const keys = Mods.toSelectKeys(items)
  
  return Mods
    .filter(mod => keys.includes(mod.path))
    .map(mod => mod.path)
}

async function addItems(newItems?: Awaited<ReturnType<typeof Mods.requestDirs>>) {
  const modItems = items.value

  if (!newItems || !modItems) {
    return
  }

  const result = [...modItems]

  for (const [file, name] of newItems) {
    if (!modItems.some(item => item[1] === name)) {
      result.push([file, name])
    }
  }

  items.value = result
}
</script>


<style lang='scss' scoped>
.mods {
  &-button {
    margin-bottom: 10px;
  }

  &-transfer {
    justify-content: center;
  }

  &-manual-button {
    display: block;
    margin: 10px auto 0;
  }

  &-spin {
    display: block;
    font-size: 24px;
    margin: 0 auto;
  }
}
</style>

// src/renderer/pages/main/lists/components/ModsPopup.tsx
import type { ReactNode } from 'react'

import { Button, Modal, Spin, Transfer } from 'antd'
import { afcMemo, onRender, reactive } from 'react-afc'

import { mods } from '../services/mods'
import { MANUAL_MOD, MODS_POPUP_TITLE } from '../texts'

import { LOADING } from '#globalTexts/renderer'
import { config } from '#services'
import type { IFindItem } from '#types'

type Props = {
  show: boolean
  hidePopup(reload?: boolean): void
}

export const ModsPopup = afcMemo((props: Props) => {
  const titles = ['Found', 'Added']

  const state = reactive({
    items: undefined as IFindItem[] | undefined,
    targetKeys: [] as string[],
    selectedKeys: [] as string[]
  })

  onRender(loadMods)

  function render(): ReactNode {
    const { show } = props
    const { items, targetKeys, selectedKeys } = state

    return (
      <Modal
        title={items ? MODS_POPUP_TITLE : LOADING}
        onCancel={onHidePopup}
        onOk={applyChanges}
        open={show}
      >
        {items
          ? <>
            <Transfer
              dataSource={items.map(item => ({
                key: item.path,
                title: item.name
              }))}
              onChange={onChange}
              onSelectChange={onSelectChange}
              targetKeys={targetKeys}
              selectedKeys={selectedKeys}
              titles={titles}
              render={item => item.title}
              className='mods-transfer'
            />
            <Button onClick={addManual} className='mods-manual-button'>
              {MANUAL_MOD}
            </Button>
          </>
          : <Spin className='mods-spin'/>
        }
      </Modal>
    )
  }

  function loadMods(): void {
    if (props.show && !state.items) {
      setTimeout(() => {
        mods.load().then(items => {
          state.items = items
          state.targetKeys = getTargetKeys(items)
        })
      }, 500)
    }
  }

  function onHidePopup(): void {
    if (!state.items) return
    state.targetKeys = getTargetKeys(state.items)
    props.hidePopup()
  }

  function applyChanges(): void {
    if (!state.items) return
    mods.save(state.targetKeys, state.items)
    props.hidePopup(true)
  }

  function addManual(): void {
    const { items } = state
    const mod = mods.requestMod()
    if ( !mod
      || !items
      || items.find(item => item.name === mod.id)
    ) return

    state.items = [
      ...items,
      {
        name: mod.id,
        path: mod.path
      }
    ]
  }

  function onChange(nextTarget: string[]): void {
    state.targetKeys = nextTarget
  }

  function onSelectChange(source: string[], target: string[]): void {
    state.selectedKeys = [...source, ...target]
  }

  function getTargetKeys(items: IFindItem[]): string[] {
    const keys = mods.itemToKeys(items)

    return Object.values(config.mods.items)
      .filter(value => keys.includes(value.path))
      .map(value => value.path)
  }

  return render
})
