// src/renderer/pages/main/editor/components/extra/addons-content/index.vue
<template>
  <Group
    key="addons-content"
    :label="label.value"
    icon="wrench"
    @click="open = true"
  >
    <Spin v-if="!state.items" />
    <template v-else>
      <div class="main">
        <Text>
          {{ texts.addonName }}
        </Text><br>
        <Input
          type="text"
          :placeholder="texts.addonFilter"
          @blur="changeFilter($event.target?.['value'])"
        /><br>
        <Select
          class="addon-select"
          :value="state.addon"
          :options="options"
          @change="value => select(String(value))"
        />
      </div>
      <div class="grid ac-grid">
        <ContentField
          v-model="state.wheels"
          :text="texts.addonWheels"
        />
        <ContentField
          v-model="state.repairs"
          :text="texts.addonRepairs"
        />
        <ContentField
          v-model="state.fuel"
          :text="texts.addonFuel"
        />
        <ContentField
          v-model="state.water"
          :text="texts.addonWater"
        />
      </div>

      <Button
        class="save"
        type="primary"
        @click="save"
      >
        {{ texts.saveButton }}
      </Button>
    </template>
  </Group>
</template>

<script lang='ts' setup>
import type { SelectProps } from 'ant-design-vue'
import { Button, Input, Select, Typography } from 'ant-design-vue'
import { reactive, ref, watch } from 'vue'

import { useEditorStore } from '../../../../store'
import type { IActionProps } from '../../../types'
import Group from '../../group'
import type { ReadyEmits, ReadyProps } from '../../utils'
import { useReady } from '../../utils'
import texts from '../texts'
import ContentField from './content-field.vue'

import type { File } from '/mods/renderer'
import { AddonXML, DLCs, Dirs, GameTexts, Lang, Messages, XMLElement } from '/mods/renderer'
import { Spin } from '/rend/components'
import { localize } from '/utils/texts/renderer'

const { Text } = Typography

type OptionsType = SelectProps['options']

export type AddonsContentProps = ReadyProps & IActionProps

const { file, xml } = defineProps<IActionProps>()
const emit = defineEmits<ReadyEmits>()

const { mod } = useEditorStore().info
const open = ref(false)
const options = ref<OptionsType>([])

const defaultVal = {
  wheels: 0,
  repairs: 0,
  fuel: 0,
  water: 0
}

const state = reactive({
  ...defaultVal,
  items: null as File[] | null,
  addon: ''
})

const label = localize({
  value: {
    [Lang.ru]: 'Содержимое аддонов',
    [Lang.en]: 'Addons content',
    [Lang.de]: 'Addon-Inhalt',
    [Lang.ch]: '附加组件的内容'
  }
})

let allOptions: OptionsType = []

useReady(emit)

watch(open, async () => {
  if (state.items) return

  const items = await getAddons(file.name, mod, isInstalled)
  const data = await getAddonData(items[0])

  allOptions = options.value = await initOptions(items)
  state.items = items
  state.addon = items[0].name
  state.wheels = data.wheels
  state.repairs = data.repairs
  state.fuel = data.fuel
  state.water = data.water
})

async function changeFilter(value = '') {
  if (!state.items || !allOptions) return
  options.value = allOptions.filter(({ label }) => label.toLowerCase().includes(value.toLowerCase()))
}

async function select(addonName: string) {
  const data = await getAddonData(getItem(addonName))

  state.addon = addonName
  state.wheels = data.wheels
  state.repairs = data.repairs
  state.fuel = data.fuel
  state.water = data.water
}

async function save() {
  const addon = getItem(state.addon)
  const xml = await getAddonXML(addon)

  if (!xml) throw new Error('DOM is undefined')
  if (!addon) throw new Error('Path to addon not found')
  
  let TruckData = xml.TruckData
  let hasAny = false

  if (!TruckData) {
    xml.appendTag('TruckData')
    TruckData = xml.TruckData!
  }

  if (state.fuel === 0) {
    TruckData.FuelCapacity = undefined
  }
  else {
    TruckData.FuelCapacity = state.fuel
    hasAny = true
  }

  if (state.water === 0) {
    TruckData.WaterCapacity = undefined
  }
  else {
    TruckData.WaterCapacity = state.water
    hasAny = true
  }

  if (state.wheels === 0) {
    TruckData.WheelRepairsCapacity = undefined
  }
  else {
    TruckData.WheelRepairsCapacity = state.wheels
    hasAny = true
  }

  if (state.repairs === 0) {
    TruckData.RepairsCapacity = undefined
  }
  else {
    TruckData.RepairsCapacity = state.repairs
    hasAny = true
  }

  if (!hasAny && !TruckData.hasAttrs()) {
    TruckData.remove()
  }

  await addon.write(xml.baseXML)
  Messages.success(texts.changed)
}

function isInstalled(addonXML: AddonXML): boolean {
  const InstallSocket = addonXML.GameData?.InstallSocket
  if (!InstallSocket) return false

  const type = InstallSocket.Type || 'no-type'
  return Boolean(
    xml.GameData?.AddonSockets?.some(
      ({ Sockets }) => Sockets.some(
        ({ Names }) => Names.includes(type)
      )
    )
  )
}

async function initOptions(items: File[]): Promise<OptionsType> {
  return await Promise.all(
    items.map(async addon => ({
      value: addon.name,
      label: await getAddonName(addon)
    }))
  )
}

async function getAddonName(addon: File): Promise<string | undefined> {
  const xml = await getAddonXML(addon)
  const uiDesc = xml?.GameData?.UiDesc
  const key = uiDesc ? uiDesc.UiName : undefined

  return GameTexts.get(key, mod) || addon.name
}

function getItem(name?: string): File | undefined {
  return state.items?.filter(item => item.name === name ?? state.addon)[0]
}

async function getAddonData(file?: File) {
  if (!file) return defaultVal

  const addonXML = await AddonXML.from(file)
  if (!addonXML) return defaultVal

  let TruckData = addonXML.TruckData
  if (!TruckData) {
    addonXML.appendTag('TruckData')
    TruckData = addonXML.TruckData!
  }

  const wheels = TruckData.WheelRepairsCapacity
  const repairs = TruckData.RepairsCapacity
  const fuel = TruckData.FuelCapacity
  const water = TruckData.WaterCapacity

  return {
    ...defaultVal,

    ...wheels ? { wheels } : {},
    ...repairs ? { repairs } : {},
    ...fuel ? { fuel } : {},
    ...water ? { water } : {}
  }
}

async function getAddonXML(file?: File): Promise<AddonXML | undefined> {
  const addonFile = file ?? getItem()
  if (!await addonFile?.exists()) return

  return await AddonXML.from(addonFile!)
}

async function getAddons(truckName: string, mod?: string, filter?: (xml: AddonXML) => boolean): Promise<File[]> {
  const allAddons: File[] = []
  const out: File[] = []
  const tuningDir = Dirs.classes.dir(`trucks/${truckName}_tuning`)

  if (await tuningDir.exists()) {
    for (const entry of await tuningDir.read()) {
      if (await entry.isDir()) continue
      allAddons.push(entry.asFile())
    }
  }

  const baseDir = Dirs.classes.dir('trucks/addons')
  if (await baseDir.exists()) {
    for (const entry of await baseDir.read()) {
      if (await entry.isDir()) continue
      allAddons.push(entry.asFile())
    }
  }

  for (const dlc of DLCs) {
    const DLCTrucks = dlc.dir.dir('classes/trucks')

    if (await DLCTrucks.exists()) {
      const DLCBasic = DLCTrucks.dir('addons')

      if (await DLCBasic.exists()) {
        for (const entry of await DLCBasic.read()) {
          if (await entry.isDir()) continue
          allAddons.push(entry.asFile())
        }
      }

      for (const entry of await DLCTrucks.read()) {
        if (!await entry.isDir() || !entry.basename().endsWith('_tuning')) continue

        for (const innerEntry of await entry.asDir().read()) {
          if (await innerEntry.isDir()) continue
          allAddons.push(innerEntry.asFile())
        }
      }
    }
  }

  if (mod) {
    for (const item of await Dirs.modsTemp.dir(mod, 'classes').findFiles({ ext: 'xml', recursive: true })) {
      const element = await XMLElement.from(item)
      
      if (element?.has('TruckAddon')) {
        allAddons.push(item)
      }
    }
  }

  for (const addon of allAddons) {
    if (filter) {
      const xml = await AddonXML.from(addon)
      if (xml && filter(xml)) out.push(addon)
    }
    else {
      out.push(addon)
    }
  }

  return out
}
</script>

<style lang='scss' scoped>
.main {
  margin-bottom: 10px;
  text-align: center;
}

.ac-grid {
  justify-content: space-around;
}

.save {
  display: block !important;
  margin: 15px auto 0;
}

.addon-select {
  margin-top: 10px;
}
</style>

// src/renderer/templates/actions/addonsContent.tsx
import type {ChangeEvent, FocusEvent} from 'react'

import {Button, Input, message, Select, Spin, Typography} from 'antd'
import type {DefaultOptionType} from 'antd/lib/select'
import type {AnyNode, Cheerio, CheerioAPI} from 'cheerio'
import {load} from 'cheerio'
import {afcMemo, afterDraw, createState} from 'react-afc'
import {getGameText} from 'scripts/helpers'
import {localize} from 'scripts/localize'
import {main} from 'scripts/main'
import type {ActionProps, FindItem} from 'types'

import {createAction} from './createAction'
import {actionTexts} from './texts'

const { Text } = Typography

const {
    readFileSync, join, writeFileSync, existsSync,
    basename, readdirSync, isDirectory
} = window.service
const { paths, findInDir } = main
const {
    ADDON_NAME,
    ADDON_WHEELS,
    ADDON_FUEL,
    ADDON_REPAIRS,
    ADDON_CHANGE_BUTTON,
    ADDON_FILTER,
    CHANGED
} = actionTexts

interface ContentFieldProps {
    text: string
    value: string
    onChange(value: string): void
}

const ContentField = afcMemo<ContentFieldProps>(props => {
    function onChangeValue(e: ChangeEvent<HTMLInputElement>) {
        props.onChange(e.target.value)
    }
    
    return () => (
        <div className='grid ac-content'>
            <Text>
                {props.text}
            </Text>
            <Input
                type='number'
                onChange={onChangeValue}
                value={props.value}
            />
        </div>
    )
})

export const AddonsContent = createAction({
    name: localize({
        RU: 'Содержимое аддонов',
        EN: 'Addons content',
        DE: 'Addon-Inhalt',
        CH: '附加组件的内容'
    }),
    id: 'addons-content',
    minHeight: 200,
    minWidth: 350,
    imgSRC: require('images/icons/wrench.png'),
    isActive() {
        return true
    }
}, afcMemo((props: ActionProps) => {
    let options: DefaultOptionType[] = []
    const [state, setState] = createState({
        items: null as FindItem[],
        selectedAddon: '',
        filter: '',
        wheels: '',
        repairs: '',
        fuel: ''
    })

    afterDraw(() => {
        const { filePath, currentMod } = props

        if (state.items) return

        setTimeout(() => {
            const items = getAddons(basename(filePath, '.xml'), currentMod, isInstalled)
            const data = getAddonData(items[0].path)

            options = initOptions(items)
            setState({
                items,
                selectedAddon: items[0].name,
                wheels: data.wheels,
                repairs: data.repairs,
                fuel: data.fuel
            })
        }, 500)
    })

    const onChangeWheels = (wheels: string) => setState({ wheels })
    const onChangeRepairs = (repairs: string) => setState({ repairs })
    const onChangeFuel = (fuel: string) => setState({ fuel })
    const onBlurFilter = (e: FocusEvent<HTMLInputElement>) => {
        const filter = e.target.value
        const includesFilter = (item: FindItem) => getAddonName(item).toLowerCase().includes(filter.toLowerCase())
        options = initOptions(state.items.filter(includesFilter))
        setState({ filter })
    }
    
    return () => {
        const { selectedAddon, wheels, repairs, fuel, items } = state

        if (!items)
            return <Spin className='mods-spin' />

        return <>
            <div className='ac-main'>
                <Text>
                    {ADDON_NAME}
                </Text><br/>
                <Input
                    type='text'
                    onBlur={onBlurFilter}
                    className='ac-content'
                    placeholder={ADDON_FILTER}
                /><br/><br/>
                <Select
                    value={selectedAddon}
                    onChange={selectAddon}
                    options={options}
                />
            </div>
            <div className='grid ac-grid'>
                <ContentField text={ADDON_WHEELS} value={wheels} onChange={onChangeWheels} />
                <ContentField text={ADDON_REPAIRS} value={repairs} onChange={onChangeRepairs} />
                <ContentField text={ADDON_FUEL} value={fuel} onChange={onChangeFuel} />
            </div>

            <Button
                className='ac-save'
                onClick={saveChanges}
                type='primary'
            >
                {ADDON_CHANGE_BUTTON}
            </Button>
        </>
    }

    function selectAddon(name: string) {
        const data = getAddonData(getItem(name).path)
        setState({
            selectedAddon: name,
            wheels: data.wheels,
            repairs: data.repairs,
            fuel: data.fuel
        })
    }

    function isInstalled(dom: CheerioAPI) {
        const installSocket = dom('InstallSocket')

        if (!installSocket.length)  
            return false

        const type = installSocket.attr('Type')
        const el = props.dom(`Socket[Names*="${type}"]`)

        return el.length > 0
    }

    function saveChanges() {
        const { selectedAddon, fuel, wheels, repairs } = state
        const pathToAddon = getItem(selectedAddon).path
        const DOM = getDOM(pathToAddon)
        let TruckData = DOM('TruckAddon TruckData')

        if (!TruckData.length) {
            DOM('TruckAddon').eq(0).append('<TruckData></TruckData>')
            TruckData = DOM('TruckAddon TruckData').eq(0)
        }

        if (fuel && fuel !== '0')
            TruckData.attr('FuelCapacity', fuel)
        else if (TruckData.attr('FuelCapacity'))
            TruckData.removeAttr('FuelCapacity')

        if (wheels && wheels !== '0')
            TruckData.attr('WheelRepairsCapacity', wheels)
        else if (TruckData.attr('WheelRepairsCapacity'))
            TruckData.removeAttr('WheelRepairsCapacity')

        if (repairs && repairs !== '0')
            TruckData.attr('RepairsCapacity', repairs)
        else if (TruckData.attr('RepairsCapacity'))
            TruckData.removeAttr('RepairsCapacity')

        if ((!fuel || fuel === '0') && (!wheels || wheels === '0') && (!repairs || repairs === '0') && TruckData.attr())
            TruckData.remove()

        writeFileSync(pathToAddon, DOM.html())
        message.success(CHANGED)
    }

    function initOptions(items: FindItem[]): DefaultOptionType[] {
        if (!items)
            return []

        return items.map(addon => ({
            value: addon.name,
            label: getAddonName(addon)
        }))
    }

    function getAddonName(addon: FindItem) {
        const dom = getDOM(addon.path)
        const uiDesc = dom('UiDesc')
        const key = uiDesc.length ? uiDesc.attr('UiName') : null

        return getGameText(key, props.currentMod) || addon.name
    }

    function getItem(name?: string) {
        const { items, selectedAddon } = state
        const itemName = name ?? selectedAddon
        return items.filter(item => item.name === itemName)[0]
    }

    function getAddonData(path?: string) {
        const DOM = getDOM(path)
        let TruckData: Cheerio<AnyNode>

        if (!DOM) {
            return {
                wheels: '',
                repairs: '',
                fuel: ''
            } 
        }

        TruckData = DOM('TruckAddon TruckData')
        if (!TruckData.length) {
            DOM('TruckAddon').eq(0).append('<TruckData></TruckData>')
            TruckData = DOM('TruckAddon TruckData').eq(0)
        }

        const wheels = TruckData.attr('WheelRepairsCapacity') ?? '0'
        const repairs = TruckData.attr('RepairsCapacity') ?? '0'
        const fuel = TruckData.attr('FuelCapacity') ?? '0'

        return {
            wheels,
            repairs,
            fuel
        }
    }

    function getDOM(path?: string) {
        const filePath = path ?? getItem().path

        if (!existsSync(filePath))  
            return
        
        return load(readFileSync(filePath), { xmlMode: true })
    }

    function getAddons(truckName: string, modId?: string, filter?: (fileDOM: CheerioAPI) => boolean) {
        const allAddons: FindItem[] = []
        const out: FindItem[] = []
        const pathToTuning = join(paths.classes, `trucks/${truckName}_tuning`)

        if (existsSync(pathToTuning)) {
            allAddons.push(...readdirSync(pathToTuning).map(item => {
                if (isDirectory(join(pathToTuning, item)))
                    return null

                return {
                    name: item,
                    path: join(pathToTuning, item)
                }
            })) 
        }

        const pathToBasic = join(paths.classes, 'trucks/addons')
        if (existsSync(pathToBasic)) {
            allAddons.push(...readdirSync(pathToBasic).map(name => ({
                name,
                path: join(pathToBasic, name)
            }))) 
        }

        readdirSync(paths.dlc).forEach(dlcFolder => {
            const pathToDLCTrucks = join(paths.dlc, dlcFolder, 'classes/trucks')
            if (existsSync(pathToDLCTrucks)) {
                const pathToDLCBasic = join(pathToDLCTrucks, 'addons')
                if (existsSync(pathToDLCBasic)) {
                    allAddons.push(...readdirSync(pathToDLCBasic).map(name => ({
                        name,
                        path: join(pathToDLCBasic, name)
                    })))
                }

                readdirSync(pathToDLCTrucks).forEach(item => {
                    if (isDirectory(join(pathToDLCTrucks, item)) && item.endsWith('_tuning')) {
                        allAddons.push(...readdirSync(join(pathToDLCTrucks, item)).map(name => ({
                            name,
                            path: join(pathToDLCTrucks, item, name)
                        })))
                    }
                })
            }
        })

        if (modId) {
            allAddons.push(...findInDir(join(paths.modsTemp, modId, 'classes'), false, '.xml', true).filter(item => {
                if (!existsSync(item.path))
                    return false

                return !!load(readFileSync(item.path), {xmlMode: true})('TruckAddon').length
            })) 
        }

        allAddons.forEach(addon => {
            if (filter) {
                if (filter(load(readFileSync(addon.path), { xmlMode: true })))
                    out.push(addon)
            }
            else {
                out.push(addon)
            }
        })
    
        return out
    }
}))
