// src/renderer/components/Language.tsx
import {memo} from 'react'

import type {RadioChangeEvent} from 'antd'
import {Radio, Select} from 'antd'
import {Lang} from 'enums'
import {globalTexts} from 'globalTexts/renderer'
import {config} from 'scripts/config'
import {main} from 'scripts/main'

const { relaunchApp } = main
const { LANGUAGE_LABEL } = globalTexts

interface Props {
    isSetup?: boolean;
}

const langOptions = Object.keys(Lang).map(lang => ({
    label: lang,
    value: lang
}))


function onChangeRadio(event: RadioChangeEvent) {
    config.lang = event.target.value
    relaunchApp()
}

function changeLang(value: Lang) {
    config.lang = value
    relaunchApp()
}

/** Выбор язка программы */
export const Language = memo((props: Props) => (
    <div>
        {props.isSetup 
            ? <Radio.Group
                defaultValue={config.lang}
                onChange={onChangeRadio}
                optionType='button'
                buttonStyle='solid'
                options={langOptions}
            />
            : <>
                <label htmlFor='lang-select' className='lang-label'>
                    {LANGUAGE_LABEL}
                </label>
                <Select
                    id='lang-select'
                    onChange={changeLang}
                    value={config.lang}
                    size='large'
                    options={langOptions}
                />
            </>
        }
    </div>
))

// src/renderer/components/language/index.vue
<template>
  <div>
    <Radio.Group
      v-if='props.isSetup'
      :value='Config.ref.lang'
      :options='options'
      @change='changeLang($event.target.value)'
      option-type='button'
      button-style='solid'
    />
    <template v-else>
      <label for='lang-select' class='lang-label'>
        {{ texts.languageLabel }}
      </label>
      <Select
        id='lang-select'
        @change='value => changeLang(parseStrToLang(value?.toString() || ""))'
        :value='Config.ref.lang'
        :options='options'
        size='large'
      />
    </template>
  </div>
</template>

<script lang='ts' setup>
import { Radio, Select } from 'ant-design-vue'
import texts from './texts'
import { useLangToOptions } from './utils'
import { Config, Lang, parseStrToLang } from '/mods/renderer'

type Props = {
  isSetup?: boolean
}

const props = defineProps<Props>()
const options = useLangToOptions(Lang)

function changeLang(newLang: Lang) {
  if (newLang === Config.lang) return
  Config.lang = newLang
}
</script>

<style lang='scss' scoped>
.lang-label {
  color: black;
  display: inline-block;
  margin-right: 15px;
  font-size: 1rem;
}
</style>
