// src/renderer/pages/setup/game-folder.vue
<template>
  <div class="game-folder">
    <Button
      class="folder-button"
      type="primary"
      size="large"
      @click="onFolderClick"
    >
      <template #icon>
        <FolderFilled />
      </template>
      {{ texts.gameFolderLabel }}
    </Button>
    <Button
      type="primary"
      size="large"
      @click="onFileClick"
    >
      <template #icon>
        <FileFilled />
      </template>
      initial.pak
    </Button>
  </div>
</template>

<script lang='ts' setup>
import { FileFilled, FolderFilled } from '@ant-design/icons-vue'
import { Button } from 'ant-design-vue'

import texts from './texts'
import type { IFolder } from './types'

import type { Dir, File } from '/mods/renderer'
import { Dialogs, Messages } from '/mods/renderer'

type Emits = {
  change: [path: string]
}

const emit = defineEmits<Emits>()

async function onFolderClick() {
  const data = await getGameFolder()
  if (!data) return
  emit('change', data.initial.path)
}

async function onFileClick() {
  const data = await getInitialPak()
  if (!data) return
  emit('change', data.initial.path)
}

async function getInitialPak(): Promise<IFolder | undefined> {
  const initial = Dialogs.getInitial()

  if (!initial || initial.basename() !== 'initial.pak' || !await initial.exists()) {
    Messages.error(texts.invalidInitialError)
    return
  }
  return { initial, dir: initial.root }
}

async function getGameFolder(): Promise<IFolder | undefined> {
  const requested = Dialogs.getDir()

  if (!requested) {
    Messages.error(texts.invalidFolderError)
    return
  }
  const existed = await findInitial(requested)

  if (!existed) {
    Messages.error(texts.invalidFolderError)
    return
  }

  return {
    dir: existed.root,
    initial: existed
  }
}

async function findInitial(dir: Dir): Promise<File | undefined> {
  const parts = ['steamapps', 'common', 'SnowRunner', 'en_us', 'preload', 'paks', 'client', 'initial.pak']
  const len = parts.length
  for (let i = 0; i < len; i++) {
    const file = dir.file(...parts)
    if (await file.exists()) return file
    parts.shift()
  }
}
</script>

<style lang='scss' scoped>
.game-folder {
  margin-top: 40px;
}

.folder-button {
  margin-right: 30px;
}
</style>

// src/renderer/pages/setup/components/GameFolder.tsx
import { memo } from "react";

import { FileFilled, FolderFilled } from "@ant-design/icons";
import { Button } from "antd";
import getPreload from "scripts/getPreload";
import type IFolder from "types/IFolder";

import texts from "../texts";

const { GAME_FOLDER_LABEL } = texts;
const preload = getPreload<IGameDataProvider>();

interface IGameDataProvider {
    getInitial(): IFolder;
    getGameFolder(): IFolder;
}

interface IProps {
    onChange(path: string): void;
}

export default memo((props: IProps) => {
    const { onChange } = props;

    return (
        <div className="game-folder">
            <Button
                className="folder-button"
                type="primary"
                icon={<FolderFilled />}
                size="large"
                onClick={() => getFolder(onChange)}
            >
                {GAME_FOLDER_LABEL}
            </Button>
            <Button
                type="primary"
                icon={<FileFilled />}
                size="large"
                onClick={() => getPak(onChange)}
            >
                initial.pak
            </Button>
        </div>
    );
});

function getPak(onChange: IProps["onChange"]) {
    const data = preload.getInitial();
    if (!data) return;

    data.folder = data.initial;

    onChange(data.initial);
}

function getFolder(onChange: IProps["onChange"]) {
    const data = preload.getGameFolder();
    if (!data) return;

    onChange(data.initial);
}
