// src/scripts/modules/xmlEditor/components/Group.vue
<template>
    <div class='accordion-item' style='position: relative'>
        <div 
            :class='["group", "accordion-button", {collapsed: !Boolean(filter.value)}]'
            data-bs-toggle='collapse'
            :data-bs-target='`#_${groupContainerId}`'
            aria-expanded='false'
            :style='styles.headerCont'
        >
            <div class='accordion-header' :style='styles.header' :id='`_${headerId}`'>
                {{ item.groupName }}
            </div>
        </div>
        <div
            :class='["group-cont", "accordion-collapse", "collapse", {show: Boolean(filter.value)}]'
            :aria-labelledby='`_${headerId}`'
            :data-bs-parent='`#${parent}`'
            :id='`_${groupContainerId}`'
        >
            <div class='accordion-body' :id='`_${groupContentId}`'>
                <Param
                    :isExport='isExport'
                    :isExporting='isExporting'
                    v-for='param in items.params'
                    :item='param'
                    :tabs='tabs + 1'
                    :key='param.name'
                />
                <Group
                    :isExport='isExport'
                    :isExporting='isExporting'
                    v-for='groupItem in items.groups'
                    :item='groupItem'
                    :parent='`_${groupContentId}`'
                    :tabs='tabs + 1'
                    :key='groupItem.groupName'
                />
            </div>
        </div>
        <input type="checkbox" class='group-export' v-model="isExport" v-show="isExporting">
    </div>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'
import Param from './Param.vue'

export default defineComponent({
    name: 'PGroup',
    components: {
        Param
    },
    props: {
        item: Object,
        tabs: Number,
        parent: String,
        isExport: {
            type: Boolean,
            default: true
        },
        isExporting: Boolean
    },
    inject: ['filter'],
    data() {
        return {
            styles: {
                header: {
                    paddingLeft: `${this.tabs * 10}px`
                },
                headerCont: {
                    paddingLeft: `${this.tabs * 5}px`
                }
            }
        };
    },
    computed: {
        headerId() {
            return Math.round(Math.random() * 1000000)
        },
        groupContainerId() {
            return Math.round(Math.random() * 1000000)
        },
        groupContentId() {
            return Math.round(Math.random() * 1000000)
        },
        items() {
            const groups = []
            const params = []
            for (const groupItem of this.item.groupItems) {
                if (groupItem.paramType === 'group') {
                    groups.push(groupItem)
                } else {
                    params.push(groupItem)
                }
            }
            return {
                groups,
                params
            }
        }
    }
})
</script>

<style scoped>
.group-export {
    display: inline-block;
    position: absolute;
    right: 10px;
    top: 18px;
    z-index: 5;
    width: 20px !important;
}
</style>

// src/scripts/modules/editor/components/Group.tsx
import { PureComponent } from 'react'
import '../styles/Group'

import { IMainContext, MainContext } from '../MainContext'

import Parameter from './Parameter'

interface IProps {
    tabs: number
    parent: string
    item: IGroupParams
    isParentExport: boolean
    isExporting: boolean
}

interface IState {
    isExport: boolean
}

export default class Group extends PureComponent<IProps, IState> {
    static contextType = MainContext
    declare context: IMainContext

    private headerID: number
    private containerID: number
    private contentID: number
    private items: {
        groups: any[]
        params: any[]
    }
    private styles: {
        [name: string]: React.CSSProperties
    }

    constructor(props: IProps) {
        super(props)

        this.state = {
            isExport: props.isParentExport
        }
        this.styles = {
            header: { paddingLeft: `${props.tabs * 10}px` },
            headerCont: { paddingLeft: `${props.tabs * 5}px` }
        }
        this.headerID = Math.round(Math.random() * 1000000)
        this.containerID = Math.round(Math.random() * 1000000)
        this.contentID = Math.round(Math.random() * 1000000)
        this.items = this.getItems()
    }

    render() {
        const { filter } = this.context

        return this.filt(this.props.item.groupItems)?
            <div className='accordion-item' style={{position: 'relative'}}>
                <div 
                    className={`group accordion-button${!Boolean(filter)? ' collapsed':''}`}
                    data-bs-toggle='collapse'
                    data-bs-target={`#_${this.containerID}`}
                    aria-expanded='false'
                    style={this.styles.headerCont}
                >
                    <div className='accordion-header' style={this.styles.header} id={`_${this.headerID}`}>
                        {this.props.item.groupName}
                    </div>
                </div>
                <div
                    className={`group-cont accordion-collapse collapse${Boolean(filter)? ' show':''}`}
                    aria-labelledby={`_${this.headerID}`}
                    data-bs-parent={`#${this.props.parent}`}
                    id={`_${this.containerID}`}
                >
                    <div className='accordion-body' id={`_${this.contentID}`}>
                        {this.items.params.map(param => 
                            <Parameter
                                isParentExport={this.state.isExport && this.props.isParentExport}
                                isExporting={this.props.isExporting}
                                item={param}
                                tabs={this.props.tabs + 1}
                                key={param.name}
                            />
                        )}
                        
                        {this.items.groups.map(groupItem => 
                            <Group
                                isParentExport={this.state.isExport && this.props.isParentExport}
                                isExporting={this.props.isExporting}
                                item={groupItem}
                                parent={`_${this.contentID}`}
                                tabs={this.props.tabs + 1}
                                key={groupItem.groupName}
                            />
                        )}
                    </div>
                </div>
                {this.props.isExporting?
                    <input
                        type='checkbox'
                        className='group-export'
                        checked={this.state.isExport && this.props.isParentExport}
                        onChange={this.toggleExporting}
                    />
                :null}
            </div>
        :null
    }

    private toggleExporting = () => {
        if (this.props.isParentExport) {
            this.setState({
                isExport: !this.state.isExport
            })
        }
    }

    private getItems() {
        const groups = []
        const params = []
        for (const groupItem of this.props.item.groupItems) {
            if (groupItem.paramType === 'group') {
                groups.push(groupItem)
            } else {
                params.push(groupItem)
            }
        }
        return { groups, params }
    }

    private filt(items: any[]): boolean {
        const { filter } = this.context

        if (!filter) return true
        let hasItem = false

        for (const item of items) {
            if (item.paramType === 'group') {
                hasItem = this.filt(item.groupItems)
            } else {
                hasItem = item.text.toLowerCase().includes(filter)
            }
            if (hasItem) break
        }
        return hasItem
    }
}
