// src/renderer/modules/list/components/Search.tsx
import { ChangeEvent, PureComponent } from 'react'
import { t } from 'scripts'

interface IProps {
    value: string
    onChange(value: string): void
}

export class Search extends PureComponent<IProps> {
    render() {
        return (
            <div className='search'>
                <label htmlFor='search' className='form-label'>{t.SEARCH}:</label>
                <input
                    type='text'
                    id='search'
                    className='form-control'
                    value={this.props.value}
                    onChange={this.onChange}
                />
            </div>
        )
    }

    private onChange = (e: ChangeEvent<HTMLInputElement>) => {
        this.props.onChange(e.target.value)
    }
}

// src/scripts/modules/editor/components/Search.vue
<template>
    <div class='search'>
        <label for='search' class='form-label'>{{ t.SEARCH }}:</label>
        <input type='text' id='search' class='form-control' v-model='value'>
    </div>
</template>

<script lang='ts'>
import { defineComponent, inject } from 'vue'
import { t } from '../../../service'

export default defineComponent({
    inject: ['filter'],
    data() {
        const filter = inject<{value: string}>('filter')

        return {
            value: filter.value,
            t: t
        }
    },
    watch: {
        value() {
            this.filter.set(this.value)
        }
    }
})
</script>
