// src/renderer/pages/loading/index.vue
<template>
  <div class="main">
    <Title
      class="title"
      :level="4"
    >
      {{ state.title }}
    </Title>

    <Progress
      v-if="state.isDownload"
      class="progress"
      :percent="state.percent"
    />
    <Spin v-else />
  </div>
</template>

<script lang='ts' setup>
import { Progress, Typography } from 'ant-design-vue'
import { reactive } from 'vue'

import texts from './texts'

import { ProgramWindow, Windows } from '/mods/renderer'
import { Spin } from '/rend/components'
import { useWindowReady } from '/rend/utils'

import '/rend/template-script'

const { Title } = Typography
useWindowReady(ProgramWindow.loading)
useEvents()

const state = reactive({
  isDownload: false,
  percent: 0,
  title: texts.loading
})

function useEvents() {
  Windows.onLoadingSuccess(() => {
    state.percent = 0
    state.isDownload = false
    state.title = texts.loading
  })
  Windows.onLoadingDownload(() => {
    state.isDownload = true
    state.title = texts.download
  })
  Windows.onLoadingText(title => state.title = title)
  Windows.onLoadingPercent(percent => state.percent = Number(percent))
}
</script>

<style lang='scss' scoped>
.main {
  display: flex;
  width: 100%;
  height: 100%;
  text-align: center;
  justify-content: center;
  align-items: center;
  align-content: center;
  flex-wrap: wrap;
}

.progress {
  padding: 5px;
}

.title {
  width: 100%;
  margin-top: 0;
}

.spin {
  margin-top: 20px;

  &-icon {
    font-size: 40px;
    color: #2196f3;
  }
}
</style>

// src/renderer/pages/loading/index.tsx
import { LoadingOutlined } from '@ant-design/icons'
import { Progress, Spin, Typography } from 'antd'
import { pafc, useReactive } from 'react-afc'

import { ProgramWindow } from '#enums'
import $ from '#gl-texts/renderer'
import useWindowReady from '#helpers/useWindowReady'
import { helpers, ipc } from '#services'

import '#r/templateScript'
import './styles'

const { Title, Text } = Typography

const Loading = pafc(() => {
  const state = useReactive({
    loadedCount: 0,
    allCount: 0,
    percent: 0,
    title: $.LOADING,
    isDownload: false
  })
  useWindowReady(ProgramWindow.Loading)
  useIPC()

  return () => {
    const { title, isDownload, percent, loadedCount, allCount } = state

    return (
      <div className='main'>
        <Title className='title' level={4}>
          {title}
        </Title>

        {isDownload
          ? <>
            <Progress percent={percent}/>
            <div className='grid info'>
              <Text>
                {loadedCount} / {allCount}
              </Text>
            </div>
          </>
          : <Spin
            className='spin'
            indicator={<LoadingOutlined className='spin-icon' spin/>}
          />
        }
      </div>
    )
  }

  function useIPC(): void {
    ipc.on('success', () => {
      state.percent = 0
      state.loadedCount++
    })
    ipc.on('download', () => state.isDownload = true)
    ipc.on('fileName', (_, title) => state.title = title)
    ipc.on('percent', (_, percent) => state.percent = percent)
    ipc.on('count', (_, allCount) => state.allCount = allCount)
  }
})

helpers.renderComponent(<Loading/>)
