// src/scripts/modules/setup/components/Save.vue
<template>
    <div id="save">
        <button class='btn btn-primary save-button' @click='save'>
            {{ t.SAVE_BUTTON }}
        </button>
    </div>
</template>

<script lang='ts'>
import { defineComponent, toRefs } from 'vue'

import { t, mainProcess } from '../../../service'

export default defineComponent({
    props: {
        pathToInitial: {
            type: String,
            required: true
        }
    },
    setup(props) {
        const { pathToInitial } = toRefs(props)

        return {
            t,
            pathToInitial
        }
    },
    methods: {
        save() {
            if (!this.pathToInitial) {
                mainProcess.alertSync(t.NO_GAME_FOLDER)
                return;
            }

            config.paths.initial = this.pathToInitial
            mainProcess.saveInitialHash()
            mainProcess.saveBackup(true)
        }
    }
})
</script>

<style scoped>
.save-button {
    margin-top: 20px;
    margin-bottom: 60px;
}
</style>

// src/renderer/modules/setup/components/Save.tsx
import { PureComponent } from 'react'
import { mainProcess, t } from 'scripts'

const { alertSync, saveBackup } = mainProcess
const { config } = window.provider

interface IProps {
    pathToInitial: string
}

export class Save extends PureComponent<IProps> {
    render() {
        return (
            <div id='save'>
                <button className='btn btn-primary save-button' onClick={this.save}>
                    {t.SAVE_BUTTON}
                </button>
            </div>
        )
    }

    private save = () => {
        if (!this.props.pathToInitial) {
            alertSync(t.NO_GAME_FOLDER)
            return
        }

        config.initial = this.props.pathToInitial
        saveBackup(true)
    }
}
