// src/renderer/pages/main/editor/components/error-header.vue
<template>
  <Header
    :text="texts.error"
    with-back
    @back="route(Page.lists)"
  />
</template>

<script lang='ts' setup>
import { Page } from '../../enums'
import { usePageStore } from '../../store'
import texts from '../texts'

import { Header } from '/rend/components'

const { route } = usePageStore()
</script>

// src/renderer/pages/main/editor/components/ErrorHeader.tsx
import { pafcMemo, useActions } from 'react-afc'

import Header from '#components/Header'
import { Page } from '#enums'
import $ from '#gl-texts/renderer'
import { actions } from '#pages/main/store'

function ErrorHeader() {
  const { route } = useActions(actions)
  
  return () => (
    <Header
      text={$.ERROR}
      onBack={onBack}
    />
  )

  function onBack(): void {
    route(Page.lists)
  }
}

export default pafcMemo(ErrorHeader)
