// src/renderer/pages/general/editor/components/header/main-header.vue
<template>
  <Header
    :text="title"
    with-back
    @back="() => route(Page.lists)"
  >
    <template #extra>
      <Dropdown trigger="click">
        <MenuOutlined class="menu-button" />
        <template #overlay>
          <Menu mode="vertical">
            <Menu.Item @click="onReset">
              <Text>{{ texts.resetMenuItemLabel }}</Text>
              <UndoOutlined class="menu-item-icon" />
            </Menu.Item>
            <Menu.Item @click="exportFile()">
              <Text>{{ texts.export }}</Text>
              <ExportOutlined class="menu-item-icon" />
            </Menu.Item>
            <Menu.Item @click="importFile()">
              <Text>{{ texts.import }}</Text>
              <ImportOutlined class="menu-item-icon" />
            </Menu.Item>
            <FilesMenu v-if="Config.advancedMode" />
          </Menu>
        </template>
      </Dropdown>
      <Button
        id="save"
        class="menu-save-button"
        type="text"
        shape="circle"
        @click="onSave()"
      >
        <template #icon>
          <SaveOutlined style="font-size: 25px" />
        </template>
      </Button>
    </template>
  </Header>
</template>

<script lang='ts' setup>
import { ExportOutlined, ImportOutlined, MenuOutlined, SaveOutlined, UndoOutlined } from '@ant-design/icons-vue'
import { Button, Dropdown, Menu, Modal, Typography } from 'ant-design-vue'
import { storeToRefs } from 'pinia'
import { EditedAction, useEditorStore, usePageStore } from '../../../store'
import texts from '../../texts'
import { ExportUtils, ImportUtils, ResetUtils, SaveUtils } from '../../utils'
import FilesMenu from '../files-menu'
import type { TruckXML } from '/mods/renderer'
import { Archive, Config, Edited, File, GameTexts, Messages, Mods, Page, TruckFileType } from '/mods/renderer'
import { Header } from '/rend/components'
import { lastItem, prettyString } from '/utils/renderer'

const { Text } = Typography

export type MainHeaderProps = {
  xml: TruckXML
  file: File
}

const { xml, file } = defineProps<MainHeaderProps>()
const { route } = usePageStore()
const editorStore = useEditorStore()
const { showMessages, info, editedAction } = storeToRefs(editorStore)
const { setIsSaving, setEditedAction } = editorStore

defineExpose({
  save: onSave,
  reset: reset,
  import: importFile,
  export: exportFile
})

const mod = Mods.findByFile(file)
const title = getMainTitle()

async function onSave(updateFiles = true) {
  const hideLoading = showMessages.value
    ? Messages.loading(texts.savingMessage)
    : () => {}

  setIsSaving(true)

  try {
    await save(updateFiles)
    success(texts.successSaveFiles)
  } catch (error: any) {
    Messages.error(error)
  }

  setIsSaving(false)
  hideLoading()
}

async function save(updateFiles = true) {
  await SaveUtils.emitSave()

  if (updateFiles) {
    if (info.value.mod) {
      await Archive.updateFiles(info.value.mod)
    }

    await Archive.updateFiles()
  }

  switch (editedAction.value) {
    case EditedAction.markAsEdited:
      Edited.markAsEdited(file, xml.Type === TruckFileType.trailer)

      break
    case EditedAction.markAsNotEdited:
      Edited.markAsNotEdited(file)
      
      break
  }

  setEditedAction(EditedAction.markAsEdited)
}

function getMainTitle(): string {
  if (xml.GameData?.UiDesc) {
    const text = xml.GameData.UiDesc.UiName ?? xml.GameData.UiDesc.DefaultRegion?.UiName

    return GameTexts.get(text, Mods.getModID(file)) ?? text ?? 'TITLE_ERROR'
  }

  const separator = file.path.includes('/') ? '/' : '\\'

  return prettyString(new File(lastItem(file.path.split(separator))!).name).toUpperCase()
}

async function importFile(toImport?: File) {
  try {
    await ImportUtils.importFile(file, toImport)
    success(texts.wasImported)
  } catch (error: any) {
    Messages.error(error)
  }
}

async function exportFile(toExport?: File) {
  try {
    await ExportUtils.exportFile(file, toExport)
    success(texts.wasExported)
  } catch (error: any) {
    Messages.error(error)
  }
}

async function reset() {
  try {
    await ResetUtils.emit(ResetUtils.globalID)
    setEditedAction(EditedAction.markAsNotEdited)

    if (showMessages.value) {
      Messages.success(texts.successReset)
    }
  } catch (error: any) {
    Messages.error(error)
  }
}

function success(text: string) {
  if (showMessages.value) {
    Messages.success(text)
  }
}

function onReset() {
  if (mod) {
    return
  }

  Modal.confirm({
    okText: texts.ok, cancelText: texts.cancel,
    title: texts.resetConfirmMessage,
    onOk: reset
  })
}
</script>

// src/renderer/pages/main/editor/components/MainHeader.tsx
import type { ReactNode } from 'react'

import {
  ExportOutlined,
  FileOutlined,
  ImportOutlined,
  MenuOutlined,
  MoreOutlined,
  RightOutlined,
  SaveOutlined,
  UndoOutlined
} from '@ant-design/icons'
import type { MenuProps } from 'antd'
import { Button, Dropdown, Menu, message, Modal, Tooltip } from 'antd'
import type { ItemType } from 'antd/lib/menu/hooks/useItems'
import type { CheerioAPI } from 'cheerio'
import { load } from 'cheerio'
import { Bridge } from 'emr-bridge/renderer'
import { afcMemo, onRender, ref, useActions } from 'react-afc'

import { actions as reduxActions } from '../../store'
import type { ResetList } from '../helpers/getResetProvider'
import { importService } from '../services/import'
import { xmlFiles } from '../services/xmlFiles'
import {
  ACTIONS_MENU,
  IMPORT,
  PATH_TO_SAVE_NOT_FOUND,
  RESET_CONFIRM_MESSAGE,
  SAVING_MESSAGE,
  SUCCESS_RESET,
  SUCCESS_SAVE_FILES,
  WAS_EXPORTED
} from '../texts'

import { Header } from '#components/Header'
import { Page, PreloadType } from '#enums'
import { EXPORT, OPEN_BUTTON, RESET_MENU_ITEM_LABEL, SAVE_BUTTON } from '#globalTexts/renderer'
import { config, helpers, preload, system, xml } from '#services'
import type { IEditorPreload, IMPC, IXMLTemplate, TemplateParams } from '#types'

const bridge = Bridge.as<IMPC>()
const { confirm } = Modal
const { watchFile } = preload.get<IEditorPreload>(PreloadType.editor)

type Props = {
  fileDOM: CheerioAPI
  filePath: string
  mod: string
  dlc: string
  actions: IXMLTemplate['actions']
  tableItems: TemplateParams
  resetList: ResetList
}

export const MainHeader = afcMemo((props: Props) => {
  const {
    fileDOM, mod, dlc, actions, filePath,
    tableItems, resetList
  } = props
  
  let menuItems: MenuProps['items']
  const title = getMainTitle(fileDOM, filePath, mod)

  const action = ref<ReactNode>(null)
  xmlFiles.subscribe()

  onRender(() => {
    menuItems = [
      {
        label: ACTIONS_MENU,
        icon: <MoreOutlined/>,
        key: 'actions',
        children: actions?.map(item => ({
          key: `action-${item.data.id}`,
          label: item.data.name,
          icon: item.data.imgSRC
            ? <img src={item.data.imgSRC}/>
            : <RightOutlined/>,
          onClick() {
            action.value = <item.Component
              filePath={filePath}
              currentMod={mod}
              dom={fileDOM}
            />
          }
        }))
      },
      {
        onClick: !mod ? onReset : () => null,
        icon: <UndoOutlined/>,
        label: RESET_MENU_ITEM_LABEL,
        key: 'reset'
      },
      {
        onClick: onExportFile,
        icon: <ExportOutlined/>,
        label: EXPORT,
        key: 'export'
      },
      {
        onClick: () => importService.importFile(filePath, fileDOM, actions),
        icon: <ImportOutlined/>,
        label: IMPORT,
        key: 'import'
      },
      ...ifAdvanced({
        key: 'files',
        label: OPEN_BUTTON,
        icon: <FileOutlined/>,
        children: xmlFiles.files.map(file => ({
          key: file.path,
          label: system.basename(file.path),
          icon: <img src={require(`#images/icons/${file.type}.png`)}/>,
          onClick() {
            void bridge.openPath(file.path)
            watchFile(file.path, () => window.location.reload())
          }
        }))
      })
    ]
  })

  function render(): ReactNode {
    return <>
      {action.value}
      <Header
        text={title}
        onBack={onBack}
        extra={[
          <Dropdown.Button
            key='menu'
            type='text'
            className='menu-button'
            icon={<MenuOutlined/>}
            overlay={
              <Menu
                selectable={false}
                mode='vertical'
                items={menuItems}
              />
            }
          />,
          <Tooltip title={SAVE_BUTTON} key='save'>
            <Button
              id='save'
              className='save-button'
              type='text'
              shape='circle'
              icon={<SaveOutlined/>}
              onClick={onSave}
            />
          </Tooltip>
        ]}
      />
    </>
  }

  const { route } = useActions(reduxActions)

  function onExportFile(): void {
    const pathToSave = bridge.saveEPF(system.basename(filePath, '.xml'))
    if (!pathToSave) {
      void message.error(PATH_TO_SAVE_NOT_FOUND)
      return
    }

    const exported = xml.exportToObject({
      filePath,
      shortMode: false,
      mod,
      dlc,
      fileDOM,
      templateItems: tableItems,
      actions
    })

    system.writeFileSync(pathToSave, JSON.stringify(exported, null, '\t'))
    void message.success(WAS_EXPORTED)
  }

  function onBack(): void {
    route(Page.lists)
  }

  function onReset(): void {
    confirm({
      title: RESET_CONFIRM_MESSAGE,
      onOk() {
        resetList.forEach(callback => callback())
        void message.success(SUCCESS_RESET)
      }
    })
  }

  async function onSave(): Promise<void> {
    const hideLoading = message.loading(SAVING_MESSAGE)
    await new Promise<void>(resolve => {
      setTimeout(() => {
        xmlFiles.files.forEach(file => {
          const dom = load(file.dom.html(), { xmlMode: true })
          dom('[SXMLE_ID]').map((_, el) => dom(el).removeAttr('SXMLE_ID'))
          system.writeFileSync(file.path, dom.html())
        })

        mod && bridge.updateFiles(mod)
        bridge.updateFiles()

        hideLoading()
        message.success(SUCCESS_SAVE_FILES)
        resolve()
      }, 100)
    })
  }

  function getMainTitle(DOM: CheerioAPI, path: string, modName: string): string {
    if (DOM('GameData UiDesc').length === 1) {
      const text = DOM('GameData UiDesc').attr('UiName')
      return helpers.getGameText(text, modName) ?? text ?? 'TITLE_ERROR'
    }
  
    if (path.split('/').length !== 1) {
      const a = path.split('/')
      return helpers.prettyString(a[a.length - 1].replace('.xml', '')).toUpperCase()
    }
  
    const a = path.split('\\')
    return helpers.prettyString(a[a.length - 1].replace('.xml', '')).toUpperCase()
  }
  
  function ifAdvanced(item: ItemType): ItemType[] {
    return config.settings.advancedMode ? [item] : []
  }

  return render
})
