// src/renderer/pages/main/editor/components/extra/addons-content/index.vue
<template>
  <Group
    key="addons-content"
    :label="label.value"
    icon="wrench"
    @click="open = true"
  >
    <Spin v-if="!state.items" />
    <template v-else>
      <div class="main">
        <Text>
          {{ texts.addonName }}
        </Text><br>
        <Input
          class="addon-filter"
          type="text"
          :placeholder="texts.addonFilter"
          @blur="changeFilter($event.target?.['value'])"
        /><br>
        <Select
          class="addon-select"
          :value="state.addon"
          :options="options"
          @change="value => select(String(value))"
        />
      </div>
      <div class="grid ac-grid">
        <ContentField
          :value="state.wheels"
          :text="texts.addonWheels"
          @change="state.wheels = $event"
        />
        <ContentField
          :value="state.repairs"
          :text="texts.addonRepairs"
          @change="state.repairs = $event"
        />
        <ContentField
          :value="state.fuel"
          :text="texts.addonFuel"
          @change="state.fuel = $event"
        />
        <ContentField
          :value="state.water"
          :text="texts.addonWater"
          @change="state.water = $event"
        />
      </div>

      <Button
        class="save"
        type="primary"
        @click="save"
      >
        {{ texts.saveButton }}
      </Button>
    </template>
  </Group>
</template>

<script lang='ts' setup>
import type { SelectProps } from 'ant-design-vue'
import { Button, Input, Select, Typography } from 'ant-design-vue'
import { reactive, ref, watch } from 'vue'

import { useEditorStore } from '../../../../store'
import type { IActionProps } from '../../../types'
import Group from '../../group'
import type { ReadyEmits, ReadyProps } from '../../utils'
import { useReady } from '../../utils'
import texts from '../texts'
import ContentField from './content-field.vue'

import type { File } from '/mods/renderer'
import { AddonXML, DLCs, Dirs, GameTexts, Lang, Messages, XMLElement } from '/mods/renderer'
import { Spin } from '/rend/components'
import { localize } from '/utils/texts/renderer'

const { Text } = Typography

type OptionsType = SelectProps['options']

export type AddonsContentProps = ReadyProps & IActionProps

const { file, xml } = defineProps<IActionProps>()
const emit = defineEmits<ReadyEmits>()

const { mod } = useEditorStore().info
const open = ref(false)
const options = ref<OptionsType>([])

const defaultVal = {
  wheels: 0,
  repairs: 0,
  fuel: 0,
  water: 0
}

const state = reactive({
  ...defaultVal,
  items: null as File[] | null,
  addon: ''
})

const label = localize({
  value: {
    [Lang.ru]: 'Содержимое аддонов',
    [Lang.en]: 'Addons content',
    [Lang.de]: 'Addon-Inhalt',
    [Lang.ch]: '附加组件的内容'
  }
})

let allOptions: OptionsType = []

useReady(emit)

watch(open, async () => {
  if (state.items) return

  const items = await getAddons(file.name, mod, isInstalled)
  const data = await getAddonData(items[0])

  allOptions = options.value = await initOptions(items)
  state.items = items
  state.addon = items[0].name
  state.wheels = data.wheels
  state.repairs = data.repairs
  state.fuel = data.fuel
  state.water = data.water
})

async function changeFilter(value = '') {
  if (!state.items || !allOptions) return
  options.value = allOptions.filter(({ label }) => label.toLowerCase().includes(value.toLowerCase()))
}

async function select(addonName: string) {
  const data = await getAddonData(getItem(addonName))

  state.addon = addonName
  state.wheels = data.wheels
  state.repairs = data.repairs
  state.fuel = data.fuel
  state.water = data.water
}

async function save() {
  const addon = getItem(state.addon)
  const xml = await getAddonXML(addon)

  if (!xml) throw new Error('DOM is undefined')
  if (!addon) throw new Error('Path to addon not found')
  
  let TruckData = xml.TruckData
  let hasAny = false

  if (!TruckData) {
    xml.appendTag('TruckData')
    TruckData = xml.TruckData!
  }

  if (state.fuel === 0) {
    TruckData.FuelCapacity = undefined
  }
  else {
    TruckData.FuelCapacity = state.fuel
    hasAny = true
  }

  if (state.water === 0) {
    TruckData.WaterCapacity = undefined
  }
  else {
    TruckData.WaterCapacity = state.water
    hasAny = true
  }

  if (state.wheels === 0) {
    TruckData.WheelRepairsCapacity = undefined
  }
  else {
    TruckData.WheelRepairsCapacity = state.wheels
    hasAny = true
  }

  if (state.repairs === 0) {
    TruckData.RepairsCapacity = undefined
  }
  else {
    TruckData.RepairsCapacity = state.repairs
    hasAny = true
  }

  if (!hasAny && !TruckData.hasAttrs()) {
    TruckData.remove()
  }

  await addon.write(xml.baseXML)
  Messages.success(texts.changed)
}

function isInstalled(addonXML: AddonXML): boolean {
  const InstallSocket = addonXML.GameData?.InstallSocket
  if (!InstallSocket) return false

  const type = InstallSocket.Type || 'no-type'
  return Boolean(
    xml.GameData?.AddonSockets?.some(
      ({ Sockets }) => Sockets.some(
        ({ Names }) => Names.includes(type)
      )
    )
  )
}

async function initOptions(items: File[]): Promise<OptionsType> {
  return await Promise.all(
    items.map(async addon => ({
      value: addon.name,
      label: await getAddonName(addon)
    }))
  )
}

async function getAddonName(addon: File): Promise<string | undefined> {
  const xml = await getAddonXML(addon)
  const uiDesc = xml?.GameData?.UiDesc
  const key = uiDesc ? uiDesc.UiName : undefined

  return GameTexts.get(key, mod) || addon.name
}

function getItem(name?: string): File | undefined {
  return state.items?.filter(item => item.name === name ?? state.addon)[0]
}

async function getAddonData(file?: File) {
  if (!file) return defaultVal

  const addonXML = await AddonXML.from(file)
  if (!addonXML) return defaultVal

  let TruckData = addonXML.TruckData
  if (!TruckData) {
    addonXML.appendTag('TruckData')
    TruckData = addonXML.TruckData!
  }

  const wheels = TruckData.WheelRepairsCapacity
  const repairs = TruckData.RepairsCapacity
  const fuel = TruckData.FuelCapacity
  const water = TruckData.WaterCapacity

  return {
    ...defaultVal,

    ...wheels ? { wheels } : {},
    ...repairs ? { repairs } : {},
    ...fuel ? { fuel } : {},
    ...water ? { water } : {}
  }
}

async function getAddonXML(file?: File): Promise<AddonXML | undefined> {
  const addonFile = file ?? getItem()
  if (!await addonFile?.exists()) return

  return await AddonXML.from(addonFile!)
}

async function getAddons(truckName: string, mod?: string, filter?: (xml: AddonXML) => boolean): Promise<File[]> {
  const allAddons: File[] = []
  const out: File[] = []
  const tuningDir = Dirs.classes.dir(`trucks/${truckName}_tuning`)

  if (await tuningDir.exists()) {
    for (const entry of await tuningDir.read()) {
      if (await entry.isDir()) continue
      allAddons.push(entry.asFile())
    }
  }

  const baseDir = Dirs.classes.dir('trucks/addons')
  if (await baseDir.exists()) {
    for (const entry of await baseDir.read()) {
      if (await entry.isDir()) continue
      allAddons.push(entry.asFile())
    }
  }

  for (const dlc of DLCs) {
    const DLCTrucks = dlc.dir.dir('classes/trucks')

    if (await DLCTrucks.exists()) {
      const DLCBasic = DLCTrucks.dir('addons')

      if (await DLCBasic.exists()) {
        for (const entry of await DLCBasic.read()) {
          if (await entry.isDir()) continue
          allAddons.push(entry.asFile())
        }
      }

      for (const entry of await DLCTrucks.read()) {
        if (!await entry.isDir() || !entry.basename().endsWith('_tuning')) continue

        for (const innerEntry of await entry.asDir().read()) {
          if (await innerEntry.isDir()) continue
          allAddons.push(innerEntry.asFile())
        }
      }
    }
  }

  if (mod) {
    for (const item of await Dirs.modsTemp.dir(mod, 'classes').findFiles({ ext: 'xml', recursive: true })) {
      const element = await XMLElement.from(item)
      
      if (element?.has('TruckAddon')) {
        allAddons.push(item)
      }
    }
  }

  for (const addon of allAddons) {
    if (filter) {
      const xml = await AddonXML.from(addon)
      if (xml && filter(xml)) out.push(addon)
    }
    else {
      out.push(addon)
    }
  }

  return out
}
</script>

<style lang='scss' scoped>
.main {
  margin-bottom: 10px;
  text-align: center;
}

.ac-grid {
  justify-content: space-around;
}

.save {
  display: block !important;
  margin: 15px auto 0;
}

.addon {
  &-select {
    min-width: 200px;
    margin-top: 10px;
  }

  &-filter {
    width: 200px;
  }
}
</style>

// src/main/templates/actions/addonsContent.tsx
import { ChangeEvent } from 'react'
import { load } from 'cheerio'
import memoizee from 'memoizee'
import type { Cheerio, CheerioAPI, Element, Node } from 'cheerio'
import type IFindItem from 'modules/list/types/IFindItem'
import type IActionData from '../types/IActionData'
import type IActionProps from '../types/IActionProps'
import main from 'scripts/main'
import { getIngameText } from 'scripts/funcs'
import localize from 'scripts/localize'
import ActionBase from './ActionBase'

import { Button, MenuItem, Select, SelectChangeEvent, styled } from '@mui/material'
import Container from 'modules/components/styled/Container'
import MyGrid from 'modules/components/styled/Grid'
import InputLabel from 'modules/editor/styled/InputLabel' 
import TextField from 'modules/editor/styled/AddonTextField'

const { readFileSync, join, writeFileSync, existsSync, basename, readdirSync, isDirectory } = window.service
const { paths, findInDir } = main

const ContentGrid = styled(MyGrid)({
    flexDirection: 'column',
    flexWrap: 'wrap',
    alignItems: 'center'
})

interface IState {
    items: IFindItem[]
    selectedAddon: string
    wheels: string
    repairs: string
    fuel: string
}

export const data: IActionData = {
    name: {
        RU: 'Содержимое аддонов',
        EN: 'Addons content',
        DE: 'Addon-Inhalt',
        CH: '附加组件的内容'
    },
    id: 'addons-content',
    minHeight: 200,
    minWidth: 350,
    imgSRC: require('images/icons/editor/wrench.png'),
    isActive: () => true
}

export default class AddonsContent extends ActionBase<IState> {
    private options: JSX.Element[] = []
    private styles = {
        content: { justifyContent: 'space-around' },
        mainCont: { marginBottom: '10px' },
        input: { width: '80px' }
    }

    constructor(props: IActionProps) {
        super(props, data, AddonsContent)

        this.state = {
            items: null,
            selectedAddon: '',
            wheels: '',
            repairs: '',
            fuel: ''
        }
    }

    componentDidMount() {
        setTimeout(() => {
            if (this.state.items === null) {
                const items = this.getAddons(basename(this.props.editor.filePath, '.xml'), this.props.editor.currentMod, this.isInstalled)
                const data = this.getAddonData(items[0].path)

                this.options = this.getOptions(items)
                this.setState({
                    items,
                    selectedAddon: items[0].name,
                    wheels: data.wheels,
                    repairs: data.repairs,
                    fuel: data.fuel
                })
            }
        }, 500)
    }

    render() {
        const { selectedAddon } = this.state

        return <>
            <Container style={this.styles.mainCont}>
                <InputLabel id='addon-name-label'>
                    {localize.ADDON_NAME}
                </InputLabel>
                <Select
                    labelId='addon-name-label'
                    value={selectedAddon}
                    onChange={this.selectAddon}
                    size='small'
                >
                    {this.options}
                </Select>
            </Container>
            <MyGrid style={this.styles.content}>
                <this.ContentField text={localize.ADDON_WHEELS} name='wheels'/>
                <this.ContentField text={localize.ADDON_REPAIRS} name='repairs'/>
                <this.ContentField text={localize.ADDON_FUEL} name='fuel'/>
            </MyGrid>

            <Button
                onClick={this.saveChanges}
                variant='contained'
                color='success'
            >
                {localize.ADDON_CHANGE_BUTTON}
            </Button>
        </>
    }

    private selectAddon = (e: SelectChangeEvent) => {
        const name = e.target.value
        const data = this.getAddonData(this.getItem(name).path)

        this.setState({
            selectedAddon: name,
            wheels: data.wheels,
            fuel: data.fuel,
            repairs: data.repairs
        })
    }

    private isInstalled = (dom: CheerioAPI) => {
        const installSocket = dom('InstallSocket')
        let type: string
        let el: Cheerio<Element>

        if (!installSocket.length) {
            return false
        }

        type = installSocket.attr('Type')
        el = this.props.dom(`Socket[Names*="${type}"]`)

        return !!el.length
    }

    private ContentField = (props: {text: string, name: keyof IState}) => {
        return (
            <ContentGrid>
                <InputLabel id='addon-fuel-label'>
                    {props.text}
                </InputLabel>
                <TextField
                    type='number'
                    value={this.state[props.name]}
                    onChange={this.onChange(props.name)}
                    size='small'
                    style={this.styles.input}
                />
            </ContentGrid>
        )
    }

    private onChange = memoizee((name: keyof IState) => {
        return (event: ChangeEvent<HTMLInputElement>) => {
            this.setState({
                [name]: event.target.value
            } as unknown as IState)
        }
    })

    private saveChanges = () => {
        const { selectedAddon, fuel, wheels, repairs } = this.state
        const pathToAddon = this.getItem(selectedAddon).path
        const DOM = this.getDOM(pathToAddon)
        let TruckData = DOM('TruckAddon TruckData')

        if (!TruckData.length) {
            DOM('TruckAddon').eq(0).append('<TruckData></TruckData>')
            TruckData = DOM('TruckAddon TruckData').eq(0)
        }

        if (fuel && fuel !== '0')
            TruckData.attr('FuelCapacity', fuel)
        else if (TruckData.attr('FuelCapacity'))
            TruckData.removeAttr('FuelCapacity')

        if (wheels && wheels !== '0')
            TruckData.attr('WheelRepairsCapacity', wheels)
        else if (TruckData.attr('WheelRepairsCapacity'))
            TruckData.removeAttr('WheelRepairsCapacity')

        if (repairs && repairs !== '0')
            TruckData.attr('RepairsCapacity', repairs)
        else if (TruckData.attr('RepairsCapacity'))
            TruckData.removeAttr('RepairsCapacity')

        if ((!fuel || fuel === '0') && (!wheels || wheels === '0') && (!repairs || repairs === '0') && TruckData.attr()) {
            TruckData.remove()
        }

        writeFileSync(pathToAddon, DOM.html())
    }

    private getOptions(items: IFindItem[]) {
        if (!items)
            return []

        return items.map(addon => {
            const name = this.getAddonName(addon)
            return (
                <MenuItem key={addon.name} value={addon.name}>
                    {name}
                </MenuItem>
            )
        })
    }

    private getAddonName(addon: IFindItem) {
        const { editor } = this.props
        const dom = this.getDOM(addon.path)
        const uiDesc = dom('UiDesc')
        const key = uiDesc.length ? uiDesc.attr('UiName') : null

        return getIngameText(key, editor.currentMod) || addon.name
    }

    private getItem(name?: string) {
        const { selectedAddon, items } = this.state

        if (!name)
            name = selectedAddon

        return items.filter(item => item.name === name)[0]
    }

    private getAddonData(path?: string) {
        const DOM = this.getDOM(path)
        let TruckData: Cheerio<Node>
        let wheels: string
        let repairs: string
        let fuel: string

        if (!DOM) {
            return {
                wheels: '',
                repairs: '',
                fuel: ''
            }
        }

        TruckData = DOM('TruckAddon TruckData')
        if (!TruckData.length) {
            DOM('TruckAddon').eq(0).append('<TruckData></TruckData>')
            TruckData = DOM('TruckAddon TruckData').eq(0)
        }

        wheels = TruckData.attr('WheelRepairsCapacity') || '0'
        repairs = TruckData.attr('RepairsCapacity') || '0'
        fuel = TruckData.attr('FuelCapacity') || '0'

        return {
            wheels: wheels,
            repairs: repairs,
            fuel: fuel
        }
    }

    private getDOM(path?: string) {
        if (!path)
            path = this.getItem().path

        if (!existsSync(path))
            return

        return load(readFileSync(path), { xmlMode: true })
    }

    private getAddons(truckName: string, modId?: string, filter?: (fileDOM: CheerioAPI) => boolean) {
        const allAddons: IFindItem[] = []
        const out: IFindItem[] = []
        const pathToTuning = join(paths.classes, `trucks/${truckName}_tuning`)
        let pathToBasic: string

        if (existsSync(pathToTuning)) {
            allAddons.push(...readdirSync(pathToTuning).map(item => {
                if (isDirectory(join(pathToTuning, item)))
                    return null

                return {
                    name: item,
                    path: join(pathToTuning, item)
                }
            }))
        }

        pathToBasic = join(paths.classes, `trucks/addons`)
        if (existsSync(pathToBasic)) {
            allAddons.push(...readdirSync(pathToBasic).map(name => {
                return {
                    name,
                    path: join(pathToBasic, name)
                }
            }))
        }

        for (const dlcFolder of readdirSync(paths.dlc)) {
            const pathToDLCTrucks = join(paths.dlc, dlcFolder, 'classes/trucks')
            if (existsSync(pathToDLCTrucks)) {
                const pathToDLCBasic = join(pathToDLCTrucks, 'addons')
                if (existsSync(pathToDLCBasic)) {
                    allAddons.push(...readdirSync(pathToDLCBasic).map(name => {
                        return {
                            name,
                            path: join(pathToDLCBasic, name)
                        }
                    }))
                }
                for (const item of readdirSync(pathToDLCTrucks)) {
                    if (isDirectory(join(pathToDLCTrucks, item)) && item.endsWith('_tuning')) {
                        allAddons.push(...readdirSync(join(pathToDLCTrucks, item)).map(name => {
                            return {
                                name,
                                path: join(pathToDLCTrucks, item, name)
                            }
                        }))
                    }
                }
            }
        }

        if (modId) {
            allAddons.push(...findInDir(join(paths.modsTemp, modId, 'classes'), false, '.xml', true).filter(item => {
                if (!existsSync(item.path))
                    return false

                if (load(readFileSync(item.path), {xmlMode: true})('TruckAddon').length)
                    return true

                return false
            }))
        }

        for (const addon of allAddons) {
            if (filter) {
                if (filter(load(readFileSync(addon.path), {xmlMode: true}))) {
                    out.push(addon)
                }
            }
            else {
                out.push(addon)
            }
        }

        return out
    }
}
