// src/renderer/modules/setup/components/Language.tsx
import { ChangeEvent, PureComponent } from 'react'
import { Lang, mainProcess, t } from 'scripts'

const { config } = window.provider
const { reload } = mainProcess

export class Language extends PureComponent {
    private langOptions: JSX.Element[]

    constructor(props: any) {
        super(props)

        this.langOptions = Object.keys(Lang).map(lang =>
            <option key={lang}>
                {lang}
            </option>
        )
    }

    render() {
        return (
            <div id='language'>
                <label className='form-label'>
                    {t.LANGUAGE_MENU_ITEM_LABEL}
                </label>
                <select
                    className='form-select lang-select'
                    onChange={this.changeLang}
                    value={config.lang}
                >
                    {this.langOptions}
                </select>
                <br />
            </div>
        )
    }

    private changeLang = (event: ChangeEvent<HTMLSelectElement>) => {
        config.lang = event.target.value as Lang
        reload()
    }
}

// src/scripts/modules/setup/components/Language.vue
<template>
    <div id="language">
        <label class='form-label'>
            {{ t.LANGUAGE_MENU_ITEM_LABEL }}
        </label>
        <select class='form-select lang-select' v-model='lang'>
            <option :key='lang' v-for='lang in allLangs'>
                {{ lang }}
            </option>
        </select><br>
    </div>
</template>

<script lang='ts'>
import { defineComponent } from 'vue'
import { mainProcess, Lang, t } from '../../../service'

export default defineComponent({
    setup() {
        const allLangs = Object.keys(Lang)

        return {
            allLangs,
            t
        }
    },
    computed: {
        lang: {
            get() {
                return config.lang
            },
            set(value) {
                config.lang = value
                mainProcess.reload()
            }
        }
    }
})
</script>

<style scoped>
.lang-select {
    width: 70px;
    margin: 0 auto;
}
</style>
