// src/scripts/modules/firstSteps/components/Language.vue
<template>
    <div id="language">
        <label class='form-label'>
            {{ t.LANGUAGE_MENU_ITEM_LABEL }}
        </label>
        <select class='form-select lang-select' v-model='lang'>
            <option :key='lang' v-for='lang in allLangs'>
                {{ lang }}
            </option>
        </select><br>
    </div>
</template>

<script>
import mainProcess from '../../../service/mainProcess.js';

export default {
    inject: ['t'],
    data() {
        return {
            allLangs: ['EN', 'RU', 'DE']
        };
    },
    computed: {
        lang: {
            get() {
                return config.lang;
            },
            set(value) {
                config.lang = value;
                mainProcess.call('reload');
            }
        }
    }
}
</script>

<style scoped>
.lang-select {
    width: 70px;
    margin: 0 auto;
}
</style>

// src/scripts/modules/setup/components/Language.tsx
import { ChangeEvent, PureComponent } from 'react'
import '../styles/Language.css'

import { Lang, mainProcess, t } from '@editor-service'

export default class Language extends PureComponent {
    private langOptions = Object.keys(Lang).map(lang =>
        <option key={lang}>{lang}</option>
    )

    render() {
        return (
            <div id='language'>
                <label className='form-label'>
                    {t.LANGUAGE_MENU_ITEM_LABEL}
                </label>
                <select 
                    className='form-select lang-select'
                    onChange={this.changeLang}
                    value={config.lang}
                >
                    {this.langOptions}
                </select>
                <br/>
            </div>
        )
    }

    private changeLang = (event: ChangeEvent<HTMLSelectElement>) => {
        config.lang = event.target.value as Lang
        mainProcess.reload()
    }
}
