// src/renderer/pages/update/index.tsx
import { useEffect, useState } from "react";

import { Typography, Button } from "antd";
import Window from "enums/Window";
import useWindowReady from "hooks/useWindowReady";
import config from "scripts/config";
import { render } from "scripts/helpers";
import main from "scripts/main";

import "./style.scss";
import texts from "./texts";

const { Title } = Typography;
const { updateApp: update } = main;
const { on } = window.ipc;
const { settings } = config;

const {
    ALLOW_NEW_VERSION_AUTO,
    UPDATE,
    IGNORE,
    CLOSE
} = texts;

const UpdateWindow = () => {
    useWindowReady(Window.Update);

    const [version, setVersion] = useState("");

    useEffect(initController, []);

    function initController() {
        on("content", (_event, data) => setVersion(data));
    }

    return <>
        <Title className="version-title" level={4}>
            {ALLOW_NEW_VERSION_AUTO} {` (v${version})`}
        </Title>
        <div className="buttons">
            <Button type="primary" onClick={updateProgram}>{UPDATE}</Button>
            <Button type="primary" danger onClick={ignoreUpdate}>{IGNORE}</Button>
            <Button onClick={closeWindow}>{CLOSE}</Button>
        </div>
    </>;
};

function closeWindow() {
    window.close();
}

function updateProgram() {
    update();
}

function ignoreUpdate() {
    settings.updates = false;
    window.close();
}

render(<UpdateWindow />);

// src/renderer/pages/update/index.vue
<template>
  <Title
    class="version-title"
    :level="4"
  >
    {{ texts.allowNewVersion }} (v{{ version }})
  </Title>
  <div class="buttons">
    <Button
      type="primary"
      danger
      @click="onIgnoreClick"
    >
      {{ texts.ignore }}
    </Button>
    <Dropdown>
      <template #overlay>
        <Menu @click="onUpdateClick">
          <Menu.Item key="installer">
            {{ texts.installer }}
          </Menu.Item>
          <Menu.Item key="portable">
            {{ texts.portable }}
          </Menu.Item>
        </Menu>
      </template>
      <Button type="primary">
        {{ texts.update }}<DownOutlined />
      </Button>
    </Dropdown>
  </div>
</template>

<script lang='ts' setup>
import { DownOutlined } from '@ant-design/icons-vue'
import type { MenuProps } from 'ant-design-vue'
import { Button, Dropdown, Menu, Typography } from 'ant-design-vue'
import { ref } from 'vue'

import texts from './texts'

import { Config, ProgramWindow, Updates, Windows } from '/mods/renderer'
import { useWindowReady } from '/rend/utils'

const { Title } = Typography
useWindowReady(ProgramWindow.update)
useEvents()

const version = ref('')

function useEvents() {
  Windows.onUpdateContent(data => version.value = data)
}

const onUpdateClick: MenuProps['onClick'] = ({ key }) => {
  if (!version.value) return
  void Updates.updateApp(key === 'portable')
}

function onIgnoreClick() {
  Config.checkUpdates = false
  window.close()
}
</script>

<style lang='scss'>
body {
  background: #fff;
  text-align: center;
}
</style>

<style lang='scss' scoped>
.version-title {
  margin-top: 20px;
}

.buttons {
  position: absolute;
  display: flex;
  width: 100%;
  bottom: 20px;
  justify-content: space-evenly;
}
</style>
