// src/renderer/pages/main/lists/index.tsx
import type { ReactNode } from 'react'

import { ApiOutlined, AppstoreAddOutlined, AppstoreOutlined, StarFilled } from '@ant-design/icons'
import { Tabs } from 'antd'
import { Bridge } from 'emr-bridge/renderer'
import { afcMemo, memoized, onDraw, useRedux } from 'react-afc'
import { useActions } from 'react-afc/compatible'

import { actions } from '../store'
import { selectCategory, selectGroup } from '../store/listSlice'
import { List } from './components/List'
import { Search } from './components/Search'
import { items as itemsService } from './services/items'
import {
  DLC_LIST_TITLE,
  FAVORITES_LIST_TITLE,
  MAIN_LIST_TITLE,
  MODS_LIST_TITLE,
  TRAILERS_CATEGORY_TITLE,
  TRAILERS_LIST_TITLE,
  TRUCKS_CATEGORY_TITLE,
  TRUCKS_LIST_TITLE
} from './texts'

import { Header } from '#components/Header'
import { Menu } from '#components/Menu'
import { Category, GroupTab, ProgramWindow, SrcType } from '#enums'
import { handleIPCMessage } from '#helpers/handleIPCMessage'
import { handleKey } from '#helpers/handleKey'
import { config } from '#services'
import type { IMPC } from '#types'

import './styles'

const bridge = Bridge.as<IMPC>()
const { settings } = config
const { TabPane } = Tabs

export const Lists = afcMemo(() => {
  const store = useRedux({
    category: selectCategory,
    group: selectGroup
  })

  handleIPCMessage()
  handleKey({
    key: 'Escape'
  }, () => bridge.quitApp())

  onDraw(() => {
    settings.showWhatsNew && openWhatsNew()
  })

  function render(): ReactNode {
    const { category, group } = store
    const { dlc, mods, all, main } = getItems()

    return <>
      <Menu/>

      <Header
        text={category === Category.trucks ? TRUCKS_LIST_TITLE : TRAILERS_LIST_TITLE}
        extra={<Search/>}
      />
      <Tabs
        className='tabs'
        activeKey={category}
        onChange={onChangeCategory}
      >
        <TabPane
          tab={<span>{TRUCKS_CATEGORY_TITLE}</span>}
          key={Category.trucks}
        />
        <TabPane
          tab={<span>{TRAILERS_CATEGORY_TITLE}</span>}
          key={Category.trailers}
        />
      </Tabs>
      <Tabs
        className='tabs'
        activeKey={group}
        onChange={onChangeGroup}
      >
        <TabPane
          tab={<span>
            <AppstoreOutlined className='tab-icon'/>
            {MAIN_LIST_TITLE}
          </span>}
          key={GroupTab.main}
        />
        <TabPane
          tab={<span>
            <AppstoreAddOutlined className='tab-icon'/>
            {DLC_LIST_TITLE}
          </span>}
          disabled={!settings.DLC}
          key={GroupTab.dlc}
        />
        <TabPane
          tab={<span>
            <ApiOutlined className='tab-icon'/>
            {MODS_LIST_TITLE}
          </span>}
          disabled={!settings.mods}
          key={GroupTab.mods}
        />
        <TabPane
          tab={<span>
            <StarFilled className='tab-icon'/>
            {FAVORITES_LIST_TITLE}
          </span>}
          key={GroupTab.favorites}
        />
      </Tabs>

      <List
        srcType={SrcType.main}
        items={main}
        opened={group === GroupTab.main}
      />
      <List
        srcType={SrcType.favorites}
        items={all}
        opened={group === GroupTab.favorites}
      />

      {settings.DLC &&
        <List
          srcType={SrcType.dlc}
          items={dlc}
          opened={group === GroupTab.dlc}
        />
      }
      {settings.mods &&
        <List
          srcType={SrcType.mods}
          items={mods}
          opened={group === GroupTab.mods}
        />
      }
    </>
  }

  const { setCategory, setGroup } = useActions(actions)

  function onChangeCategory(category: string): void {
    setCategory(category as Category)
  }

  function onChangeGroup(group: string): void {
    setGroup(group as GroupTab)
  }

  const getItems = memoized(
    () => {
      const main = itemsService.getMain(store.category)
      const dlc = itemsService.getDLC(store.category)
      const mods = itemsService.getMods(store.category)
      const all = [...main, ...dlc, ...mods]
      return { main, dlc, mods, all }
    },
    () => [store.category]
  )

  function openWhatsNew(): void {
    if (settings.showWhatsNew) {
      void bridge.openWindow(ProgramWindow.WhatsNew)
      settings.showWhatsNew = false
    }
  }

  return render
})

// src/renderer/pages/main/lists/index.vue
<template>
  <Header :text='category === Category.trucks ? texts.trucksListTitle : texts.trailersListTitle'>
    <template #extra>
      <Search />
    </template>
  </Header>

  <Tabs class='tabs' :active-key='category' @change='setCategory($event as Category)'>
    <TabPane :key='Category.trucks'>
      <template #tab>
        <Text>{{ texts.trucksCategoryTitle }}</Text>
      </template>
    </TabPane>
    <TabPane :key='Category.trailers'>
      <template #tab>
        <Text>{{ texts.trailersCategoryTitle }}</Text>
      </template>
    </TabPane>
  </Tabs>
  
  <Tabs class='tabs' :active-key='source' @change='setSource($event as SourceType)'>
    <TabPane :key='SourceType.main'>
      <template #tab>
        <AppstoreOutlined class='tab-icon' />
        <Text>{{ texts.mainListTitle }}</Text>
      </template>
    </TabPane>
    <TabPane :key='SourceType.dlc'>
      <template #tab>
        <AppstoreAddOutlined class='tab-icon' />
        <Text>{{ texts.dlcListTitle }}</Text>
      </template>
    </TabPane>
    <TabPane :key='SourceType.mods' :disabled='!Config.ref.useMods'>
      <template #tab>
        <ApiOutlined class='tab-icon' />
        <Text>{{ texts.modsListTitle }}</Text>
      </template>
    </TabPane>
    <TabPane :key='SourceType.favorites'>
      <template #tab>
        <StarFilled class='tab-icon' />
        <Text>{{ texts.favoritesListTitle }}</Text>
      </template>
    </TabPane>
  </Tabs>

  <List
    v-if='files'
    :src-type='source'
    :files='currentFiles'
  />
  <Spin v-else center />
</template>

<script lang='ts' setup>
import { TabPane, Tabs, Typography } from 'ant-design-vue'
import { computed, onMounted, ref, watch, watchEffect } from 'vue'

import { ApiOutlined, AppstoreAddOutlined, AppstoreOutlined, StarFilled } from '@ant-design/icons-vue'

import { Category, SourceType } from '../enums'
import { useListStore } from '../store/list'
import { List, Search } from './components'
import texts from './texts'
import { ItemsUtils } from './utils'

import type { File } from '/mods/renderer'
import { Config, Helpers, ProgramWindow, Windows } from '/mods/renderer'
import { Header, Spin } from '/rend/components'
import { useKey } from '/rend/utils'

const { Text } = Typography

interface IFiles {
  [SourceType.main]: File[]
  [SourceType.dlc]: File[]
  [SourceType.mods]: File[]
  [SourceType.favorites]: File[]
}

const { category, source, setCategory, setSource } = useListStore()
const files = ref<IFiles | null>(null)
const currentFiles = computed<File[]>(() => files.value ? files.value[source.value] : [])

watch(category, () => files.value = null)
watchEffect(async () => {
  const [main, dlc, mods] = await Promise.all([
    ItemsUtils.getMain(category.value),
    ItemsUtils.getDLC(category.value),
    ItemsUtils.getMods(category.value)
  ])
  files.value = {
    [SourceType.main]: main,
    [SourceType.dlc]: dlc,
    [SourceType.mods]: mods,
    [SourceType.favorites]: [...main, ...dlc, ...mods]
  }
})

useKey('Escape', () => Helpers.quitApp())
onMounted(() => openWhatsNew())

function openWhatsNew() {
  if (Config.openWhatsNew) {
    void Windows.openWindow(ProgramWindow.whatsNew)
    Config.openWhatsNew = false
  }
}
</script>

<style lang='scss'>
body {
  background-color: #e7ebf0;
}

.ant-tabs-nav-list {
  justify-content: space-evenly;
  width: 100%;
}
</style>

<style lang='scss' scoped>
.tabs {
  background-color: white;
  height: 54px;

  [role="tablist"] {
    margin-bottom: 0;
  }

  span {
    font-size: 18px;
  }

  &:hover {
    color: black;
  }

  div[role="tab"] {
    color: #5c5c5c;

    &:hover,
    &[aria-selected="true"] span {
      color: black;
    }
  }

  div[role="tablist"]::before {
    color: black;
  }

  :global(.ant-tabs-ink-bar) {
    background-color: black;
  }
}

.tab-icon {
  position: relative;
  font-size: 25px !important;
  top: 3px;
}
</style>
