// src/renderer/pages/general/editor/components/extra/addons-content/addons-content.vue
<template>
  <Group
    key="addons-content"
    :label="label"
    icon="wrench"
  >
    <template v-if="!hasItems(files)">
      <div
        v-if="loadStatus.isLoading"
        class="loading"
      >
        <Spin />
        <Text>{{ texts.foundAddons }}: {{ loadStatus.count }}</Text><br>
      </div>
      <div
        v-else
        class="prepare"
      >
        <Button
          class="load-btn"
          type="primary"
          @click="loadAddons"
        >
          {{ texts.load }}
        </Button>
      </div>
    </template>
    <div
      v-else
      class="wrapper"
    >
      <div class="main">
        <Input
          class="addon-filter"
          type="text"
          :placeholder="texts.addonFilter"
          @blur="changeNameFilter($event.target?.['value'])"
        /><br>
        <Select
          class="addon-select"
          :value="addon"
          :options="selectOptions"
          @change="value => selectAddon(String(value))"
        />
      </div>
      <div class="grid ac-grid">
        <ContentField
          :value="content.wheels"
          :text="texts.addonWheels"
          @change="content.wheels = $event"
          @blur="saveAddonData"
        />
        <ContentField
          :value="content.repairs"
          :text="texts.addonRepairs"
          @change="content.repairs = $event"
          @blur="saveAddonData"
        />
        <ContentField
          :value="content.fuel"
          :text="texts.addonFuel"
          @change="content.fuel = $event"
          @blur="saveAddonData"
        />
        <ContentField
          :value="content.water"
          :text="texts.addonWater"
          @change="content.water = $event"
          @blur="saveAddonData"
        />
      </div>
      <Button
        v-if="config.advancedMode"
        class="open-file-btn"
        type="primary"
        @click="openFile"
      >
        {{ texts.openFile }}
      </Button>
    </div>
  </Group>
</template>

<script lang='ts' setup>
import { LocalizationStrings } from '@localization'
import type { IFile } from '@modules/files/renderer'
import { TruckAddon, XMLElement } from '@modules/xml/renderer'
import Spin from '@renderer/components/spin.vue'
import { hasItems } from '@utilities/checks/renderer'
import { di } from '@utilities/di/container'
import { CONFIG_TOKEN, DIRS_TOKEN, DLC_TOKEN, GAME_TEXTS_TOKEN, MESSAGES_TOKEN, SYSTEM_TOKEN } from '@utilities/di/renderer/tokens'
import type { SelectProps } from 'ant-design-vue'
import { Button, Input, Select, Typography } from 'ant-design-vue'
import { storeToRefs } from 'pinia'
import { computed, reactive, ref } from 'vue'
import { useEditorStore } from '../../../../store/editor'
import type { IActionProps } from '../../../types'
import Group from '../../group/group.vue'
import type { ReadyEmits, ReadyProps } from '../../utilities'
import { useReady } from '../../utilities'
import { EXTRA_LOCALIZATION as texts } from '../localization'
import ContentField from './content-field.vue'

const { Text } = Typography

type OptionsType = SelectProps['options']

export type AddonsContentProps = ReadyProps & IActionProps

const config = di.resolve(CONFIG_TOKEN)
const { file, xml } = defineProps<IActionProps>()
const emit = defineEmits<ReadyEmits>()

const { info } = storeToRefs(useEditorStore())
const files = ref<IFile[]>([])
const addon = ref('')

const selectOptions = ref<OptionsType>([])
let allSelectOptions: OptionsType = []

const content = reactive({
	wheels: 0,
	repairs: 0,
	fuel: 0,
	water: 0
})
const defaultContent = { ...content }
const loadStatus = reactive({
	isLoading: false,
	count: 0
})
const label = computed(() => new LocalizationStrings()
	.ru('Содержимое аддонов')
	.en('Addons content')
	.de('Addon-Inhalt')
	.ch('附加组件')
	.get(config)
)

useReady(emit)

async function changeNameFilter(value = '') {
	if (!hasItems(files.value) || !allSelectOptions) {
		return
	}

	selectOptions.value = allSelectOptions
		.filter(({ label }) => label.toLowerCase().includes(value.toLowerCase()))
}

async function selectAddon(addonName: string) {
	const data = await getAddonData(getFile(addonName))

	addon.value = addonName
	content.wheels = data.wheels
	content.repairs = data.repairs
	content.fuel = data.fuel
	content.water = data.water
}

async function loadAddons() {
	if (hasItems(files.value)) {
		return
	}

	loadStatus.isLoading = true

	const onFind = () => void loadStatus.count++

	const addons = await getAddons(file.name, info.value.mod, isInstalled, onFind)
	const data = await getAddonData(addons[0])

	allSelectOptions = selectOptions.value = await initSelectOptions(addons)
	files.value = addons
	addon.value = addons[0].name

	content.wheels = data.wheels
	content.repairs = data.repairs
	content.fuel = data.fuel
	content.water = data.water

	loadStatus.isLoading = false
	loadStatus.count = 0
}

async function saveAddonData() {
	const item = getFile(addon.value)
	const xml = await getTruckAddon(item)

	if (!xml) {
		throw new Error('DOM is undefined')
	}

	if (!item) {
		throw new Error('Path to addon not found')
	}
	
	let TruckData = xml.TruckData
	let hasAny = false

	if (!TruckData) {
		xml.appendTag('TruckData')
		TruckData = xml.TruckData!
	}

	if (content.fuel === 0) {
		TruckData.FuelCapacity = undefined
	} else {
		TruckData.FuelCapacity = content.fuel
		hasAny = true
	}

	if (content.water === 0) {
		TruckData.WaterCapacity = undefined
	} else {
		TruckData.WaterCapacity = content.water
		hasAny = true
	}

	if (content.wheels === 0) {
		TruckData.WheelRepairsCapacity = undefined
	} else {
		TruckData.WheelRepairsCapacity = content.wheels
		hasAny = true
	}

	if (content.repairs === 0) {
		TruckData.RepairsCapacity = undefined
	} else {
		TruckData.RepairsCapacity = content.repairs
		hasAny = true
	}

	if (!hasAny && !TruckData.hasAttrs()) {
		TruckData.remove()
	}

	await item.write(xml.baseXML)
	di.resolve(MESSAGES_TOKEN).success(texts.changed)
}

function openFile() {
	const file = getFile(addon.value)

	if (file) {
		void di.resolve(SYSTEM_TOKEN).openFile(file.path)
	}
}

function isInstalled(addonXML: TruckAddon): boolean {
	const InstallSocket = addonXML.GameData?.InstallSocket

	if (!InstallSocket) {
		return false
	}

	const type = InstallSocket.Type || 'no-type'

	return Boolean(
		xml.GameData?.AddonSockets?.some(
			({ Sockets }) => Sockets.some(
				({ Names }) => Names.includes(type)
			)
		)
	)
}

async function initSelectOptions(items: IFile[]): Promise<OptionsType> {
	return await Promise.all(
		items.map(async addon => ({
			value: addon.name,
			label: await getAddonName(addon)
		}))
	)
}

async function getAddonName(addon: IFile): Promise<string | undefined> {
	const xml = await getTruckAddon(addon)
	const uiDesc = xml?.GameData?.UiDesc
	const key = uiDesc
		? uiDesc.UiName
		: undefined

	return di.resolve(GAME_TEXTS_TOKEN).get(key, info.value.mod) || addon.name
}

function getFile(name?: string): IFile | undefined {
	return files.value.find(item => item.name === (name || addon.value))
}

async function getAddonData(file?: IFile) {
	if (!file) {
		return defaultContent
	}

	const addonXML = await TruckAddon.from(file)

	if (!addonXML) {
		return defaultContent
	}

	let TruckData = addonXML.TruckData

	if (!TruckData) {
		addonXML.appendTag('TruckData')
		TruckData = addonXML.TruckData!
	}

	const wheels = TruckData.WheelRepairsCapacity ?? defaultContent.wheels
	const repairs = TruckData.RepairsCapacity ?? defaultContent.repairs
	const fuel = TruckData.FuelCapacity ?? defaultContent.fuel
	const water = TruckData.WaterCapacity ?? defaultContent.water

	return {
		...defaultContent,
		...wheels ? { wheels } : {},
		...repairs ? { repairs } : {},
		...fuel ? { fuel } : {},
		...water ? { water } : {}
	}
}

async function getTruckAddon(file?: IFile): Promise<TruckAddon | undefined> {
	const addonFile = file ?? getFile()

	return await addonFile?.exists()
		? TruckAddon.from(addonFile!)
		: undefined
}

async function getAddons(
	truckName: string,
	mod?: string,
	filter?: (xml: TruckAddon) => boolean,
	every?: () => void | Promise<void>
): Promise<IFile[]> {
	const dirs = di.resolve(DIRS_TOKEN)
	
	const out: IFile[] = []
	const tuningDir = dirs.classes.dir(`trucks/${truckName}_tuning`)
	const inLoading = new Set<Promise<void>>()

	function filterFile(file: IFile) {
		inLoading.add((async () => {
			async function pushToOut(file: IFile) {
				out.push(file)
				await every?.()
			}

			if (filter) {
				const xml = await TruckAddon.from(file)

				if (xml && filter(xml)) {
					await pushToOut(file)
				}
			} else {
				await pushToOut(file)
			}
		})())
	}

	if (await tuningDir.exists()) {
		for (const entry of await tuningDir.read()) {
			if (await entry.isDir()) {
				continue
			}

			filterFile(entry.asFile())
		}
	}

	const baseDir = dirs.classes.dir('trucks/addons')
	if (await baseDir.exists()) {
		for (const entry of await baseDir.read()) {
			if (await entry.isDir()) {
				continue
			}

			filterFile(entry.asFile())
		}
	}

	for (const dlc of di.resolve(DLC_TOKEN)) {
		const DLCTrucks = dlc.dir.dir('classes/trucks')

		if (await DLCTrucks.exists()) {
			const DLCBasic = DLCTrucks.dir('addons')

			if (await DLCBasic.exists()) {
				for (const entry of await DLCBasic.read()) {
					if (await entry.isDir()) {
						continue
					}

					filterFile(entry.asFile())
				}
			}

			for (const entry of await DLCTrucks.read()) {
				if (!await entry.isDir() || !entry.basename().endsWith('_tuning')) {
					continue
				}

				for (const innerEntry of await entry.asDir().read()) {
					if (await innerEntry.isDir()) {
						continue
					}

					filterFile(innerEntry.asFile())
				}
			}
		}
	}

	if (mod) {
		for (const item of await dirs.modsTemp.dir(mod, 'classes').findFiles({ ext: 'xml', recursive: true })) {
			const element = await XMLElement.from(item)
			
			if (element?.has('TruckAddon')) {
				filterFile(item)
			}
		}
	}

	await Promise.all(inLoading)
	
	return out
}
</script>

<style lang='scss' scoped>
.prepare,
.loading,
.wrapper {
	width: 100%;
	height: 100%;
	margin-bottom: 10px;
	text-align: center;
}

.ac-grid {
	justify-content: space-around;
}

.open-file-btn,
.load-btn {
	display: block !important;
	margin: 15px auto 0;
}

.addon {
	&-select {
		min-width: 200px;
		margin-top: 10px;
	}

	&-filter {
		width: 200px;
	}
}

.wrapper {
	width: 100%;
	text-align: center;

	.main {
		margin-bottom: 10px;
	}
}
</style>

// src/renderer/actions/addonsContent.tsx
import type { ChangeEvent, FocusEvent, ReactNode } from 'react'

import { Button, Input, message, Select, Spin, Typography } from 'antd'
import type { DefaultOptionType } from 'antd/lib/select'
import type { AnyNode, Cheerio, CheerioAPI } from 'cheerio'
import { load } from 'cheerio'
import { Bridge } from 'emr-bridge/renderer'
import { afcMemo, onMount, reactive } from 'react-afc'

import {
  ADDON_CHANGE_BUTTON,
  ADDON_FILTER,
  ADDON_FUEL,
  ADDON_NAME,
  ADDON_REPAIRS,
  ADDON_WHEELS,
  CHANGED
} from './texts'

import WrenchIcon from '#images/icons/wrench.png'
import { Action } from '#r/actions/Action'
import { helpers, localization, system } from '#services'
import type { IActionProps, IFindItem, IMPC } from '#types'

const bridge = Bridge.as<IMPC>()
const paths = bridge.paths
const { Text } = Typography

export class AddonsContent extends Action {
  protected name = localization.localize({
    RU: 'Содержимое аддонов',
    EN: 'Addons content',
    DE: 'Addon-Inhalt',
    CH: '附加组件的内容'
  })
  protected id = 'addons-content'
  protected minHeight = 200
  protected minWidth = 350
  protected imgSRC = WrenchIcon
  protected ActionComponent = AddonsContentComponent

  constructor() { super(); this.init() }
}

const AddonsContentComponent = afcMemo((props: IActionProps) => {
  let options = [] as DefaultOptionType[]

  const state = reactive({
    items: null as IFindItem[] | null,
    selectedAddon: '',
    filter: '',
    wheels: '',
    repairs: '',
    fuel: ''
  })

  onMount(() => {
    const { filePath, currentMod } = props
    if (state.items) return

    setTimeout(() => {
      const items = getAddons(system.basename(filePath, '.xml'), currentMod, isInstalled)
      const data = getAddonData(items[0].path)

      options = initOptions(items)
      state.items = items
      state.selectedAddon = items[0].name
      state.wheels = data.wheels
      state.repairs = data.repairs
      state.fuel = data.fuel
    }, 500)
  })

  function render(): ReactNode {
    const { items, selectedAddon, wheels, repairs, fuel } = state

    if (!items) return <Spin className='mods-spin'/>

    return <>
      <div className='ac-main'>
        <Text>
          {ADDON_NAME}
        </Text><br/>
        <Input
          type='text'
          onBlur={onBlurFilter}
          className='ac-content'
          placeholder={ADDON_FILTER}
        /><br/><br/>
        <Select
          value={selectedAddon}
          onChange={selectAddon}
          options={options}
        />
      </div>
      <div className='grid ac-grid'>
        <ContentField text={ADDON_WHEELS} value={wheels} onChange={onChangeWheels}/>
        <ContentField text={ADDON_REPAIRS} value={repairs} onChange={onChangeRepairs}/>
        <ContentField text={ADDON_FUEL} value={fuel} onChange={onChangeFuel}/>
      </div>

      <Button
        className='ac-save'
        onClick={saveChanges}
        type='primary'
      >
        {ADDON_CHANGE_BUTTON}
      </Button>
    </>
  }

  function onChangeWheels(wheels: string): void {
    state.wheels = wheels
  }
  function onChangeRepairs(repairs: string): void {
    state.repairs = repairs
  }
  function onChangeFuel(fuel: string): void {
    state.fuel = fuel
  }

  function onBlurFilter(e: FocusEvent<HTMLInputElement>): void {
    if (!state.items) return

    const filter = e.target.value
    options = initOptions(state.items.filter(item => {
      return getAddonName(item)?.toLowerCase().includes(filter.toLowerCase())
    }))
    state.filter = filter
  }

  function selectAddon(name: string): void {
    const data = getAddonData(getItem(name)?.path)
    state.selectedAddon = name
    state.wheels = data.wheels
    state.repairs = data.repairs
    state.fuel = data.fuel
  }

  function isInstalled(dom: CheerioAPI): boolean {
    const installSocket = dom('InstallSocket')
    if (!installSocket.length) return false

    const type = installSocket.attr('Type')
    const el = props.dom(`Socket[Names*="${type}"]`)

    return el.length > 0
  }

  function saveChanges(): void {
    const { selectedAddon, fuel, wheels, repairs } = state

    const pathToAddon = getItem(selectedAddon)?.path
    const DOM = getDOM(pathToAddon)
    let TruckData = DOM?.('TruckAddon TruckData')

    if (!TruckData?.length) {
      DOM?.('TruckAddon').eq(0).append('<TruckData></TruckData>')
      TruckData = DOM?.('TruckAddon TruckData').eq(0)
    }

    if (fuel && fuel !== '0') {
      TruckData?.attr('FuelCapacity', fuel)
    }
    else if (TruckData?.attr('FuelCapacity')) {
      TruckData?.removeAttr('FuelCapacity')
    }

    if (wheels && wheels !== '0') {
      TruckData?.attr('WheelRepairsCapacity', wheels)
    }
    else if (TruckData?.attr('WheelRepairsCapacity')) {
      TruckData?.removeAttr('WheelRepairsCapacity')
    }

    if (repairs && repairs !== '0') {
      TruckData?.attr('RepairsCapacity', repairs)
    }
    else if (TruckData?.attr('RepairsCapacity')) {
      TruckData?.removeAttr('RepairsCapacity')
    }

    if ((!fuel || fuel === '0') && (!wheels || wheels === '0') && (!repairs || repairs === '0') && TruckData?.attr()) {
      TruckData?.remove()
    }

    if (!pathToAddon) throw new Error('Path to addon not found')
    if (!DOM) throw new Error('DOM is undefined')

    system.writeFileSync(pathToAddon, DOM.html())
    void message.success(CHANGED)
  }

  function initOptions(items: IFindItem[]): DefaultOptionType[] {
    if (!items) return []

    return items.map(addon => ({
      value: addon.name,
      label: getAddonName(addon)
    }))
  }

  function getAddonName(addon: IFindItem): string | undefined {
    const dom = getDOM(addon.path)
    const uiDesc = dom?.('UiDesc')
    const key = uiDesc?.length ? uiDesc?.attr('UiName') : undefined

    return helpers.getGameText(key, props.currentMod) || addon.name
  }

  function getItem(name?: string): IFindItem | undefined {
    const { items, selectedAddon } = state
    const itemName = name ?? selectedAddon
    return items?.filter(item => item.name === itemName)[0]
  }

  function getAddonData(path?: string) {
    const DOM = getDOM(path)
    let TruckData: Cheerio<AnyNode>

    if (!DOM) {
      return {
        wheels: '',
        repairs: '',
        fuel: ''
      }
    }

    TruckData = DOM('TruckAddon TruckData')
    if (!TruckData.length) {
      DOM('TruckAddon').eq(0).append('<TruckData></TruckData>')
      TruckData = DOM('TruckAddon TruckData').eq(0)
    }

    const wheels = TruckData.attr('WheelRepairsCapacity') ?? '0'
    const repairs = TruckData.attr('RepairsCapacity') ?? '0'
    const fuel = TruckData.attr('FuelCapacity') ?? '0'

    return {
      wheels: wheels,
      repairs,
      fuel
    }
  }

  function getDOM(path?: string): CheerioAPI | undefined {
    const filePath = path ?? getItem()?.path ?? ''
    if (!system.existsSync(filePath)) return

    return load(system.readFileSync(filePath), { xmlMode: true })
  }

  function getAddons(truckName: string, modId?: string, filter?: (fileDOM: CheerioAPI) => boolean): IFindItem[] {
    const allAddons: IFindItem[] = []
    const out: IFindItem[] = []
    const pathToTuning = system.join(paths.classes, `trucks/${truckName}_tuning`)

    if (system.existsSync(pathToTuning)) {
      allAddons.push(...system.readdirSync(pathToTuning).map(item => {
        if (system.isDirectory(system.join(pathToTuning, item))) {
          return null
        }

        return {
          name: item,
          path: system.join(pathToTuning, item)
        }
      }) as IFindItem[])
    }

    const pathToBasic = system.join(paths.classes, 'trucks/addons')
    if (system.existsSync(pathToBasic)) {
      allAddons.push(...system.readdirSync(pathToBasic).map(name => ({
        name,
        path: system.join(pathToBasic, name)
      })))
    }

    system.readdirSync(paths.dlc).forEach(dlcFolder => {
      const pathToDLCTrucks = system.join(paths.dlc, dlcFolder, 'classes/trucks')
      if (system.existsSync(pathToDLCTrucks)) {
        const pathToDLCBasic = system.join(pathToDLCTrucks, 'addons')
        if (system.existsSync(pathToDLCBasic)) {
          allAddons.push(...system.readdirSync(pathToDLCBasic).map(name => ({
            name,
            path: system.join(pathToDLCBasic, name)
          })))
        }

        system.readdirSync(pathToDLCTrucks).forEach(item => {
          if (system.isDirectory(system.join(pathToDLCTrucks, item)) && item.endsWith('_tuning')) {
            allAddons.push(...system.readdirSync(system.join(pathToDLCTrucks, item)).map(name => ({
              name,
              path: system.join(pathToDLCTrucks, item, name)
            })))
          }
        })
      }
    })

    if (modId) {
      allAddons.push(...bridge.findInDir(system.join(paths.modsTemp, modId, 'classes'), false, '.xml', true).filter(item => {
        if (!system.existsSync(item.path)) {
          return false
        }

        return !!load(system.readFileSync(item.path), { xmlMode: true })('TruckAddon').length
      }))
    }

    allAddons.forEach(addon => {
      if (filter) {
        if (filter(load(system.readFileSync(addon.path), { xmlMode: true }))) {
          out.push(addon)
        }
      }
      else {
        out.push(addon)
      }
    })

    return out
  }

  return render
})

type ContentFieldProps = {
  text: string
  value: string
  onChange(value: string): void
}

const ContentField = afcMemo((props: ContentFieldProps) => {
  function render(): ReactNode {
    const { text, value } = props

    return (
      <div className='grid ac-content'>
        <Text>
          {text}
        </Text>
        <Input
          type='number'
          onChange={onChangeValue}
          value={value}
        />
      </div>
    )
  }

  function onChangeValue(e: ChangeEvent<HTMLInputElement>): void {
    props.onChange(e.target.value)
  }

  return render
})
