// src/renderer/pages/setup/index.tsx
import { useEffect, useState } from "react";

import { Button, Steps, Modal } from "antd";
import Header from "components/Header";
import Menu from "components/Menu";
import Window from "enums/Window";
import globalTexts from "globalTexts/renderer";
import useIPCMessage from "hooks/useIPCMessage";
import useWindowReady from "hooks/useWindowReady";
import config from "scripts/config";
import { render } from "scripts/helpers";
import main from "scripts/main";

import Language from "../../components/Language";
import GameFolder from "./components/GameFolder";
import texts from "./texts";

import "./style.scss";

const { Step } = Steps;
const { confirm } = Modal;

const { importConfig, paths, saveBackup } = main;
const { existsSync, join } = window.service;
const {
    FIRST_STEPS_DESCRIPTION,
    IMPORT_CONFIG_MESSAGE,
    GAME_DATA_STEP,
    NEXT
} = texts;
const { LANGUAGE_LABEL } = globalTexts;

const Setup = () => {
    useIPCMessage();
    useWindowReady(Window.Setup);

    const [current, setCurrent] = useState(0);

    useEffect(() => {
        setTimeout(checkExportedConfig, 500);
    }, []);

    const stepsContent = [
        <Language isSetup key="language" />,
        <GameFolder key="game-folder" onChange={save} />
    ];

    function save(path: string) {
        config.initial = path;
        saveBackup(true);
    }

    return <>
        <Menu />
        <Header text={FIRST_STEPS_DESCRIPTION} />

        <Steps className="steps" current={current}>
            <Step title={LANGUAGE_LABEL} />
            <Step title={GAME_DATA_STEP} />
        </Steps>
        <div className="steps-content">{stepsContent[current]}</div>
        <div className="steps-actions">
            {current < stepsContent.length - 1 && (
                <Button type="primary" onClick={() => setCurrent(current + 1)}>
                    {NEXT}
                </Button>
            )}
        </div>
    </>;
};

function checkExportedConfig() {
    if (existsSync(join(paths.backupFolder, "config.json"))) {
        confirm({
            title: IMPORT_CONFIG_MESSAGE,
            onOk: () => importConfig()
        });
    }
}

render(<Setup />);

// src/renderer/pages/setup/index.vue
<template>
  <Menu />
  <Header :text='texts.firstStepsDescription' />

  <Steps
    class='steps'
    :current='step'
    :items='[
      { title: texts.languageLabel },
      { title: texts.gameDataStep }
    ]'
  />
  <div class='steps-content'>
    <Language v-if='step === 0' :is-setup='true' />
    <GameFolder v-else-if='step === 1' @change='onChangeGameFolder' />
  </div>
  <div class='steps-actions'>
    <Button v-if='step === 0' type='primary' @click='step++'>
      {{ texts.next }}
    </Button>
  </div>
</template>

<script lang='ts' setup>
import { Button, Steps } from 'ant-design-vue'
import { ref } from 'vue'
import GameFolder from './game-folder.vue'
import texts from './texts'
import { Archive, Backup, Config, Helpers, ProgramWindow } from '/mods/renderer'
import { Header, Language, Menu } from '/rend/components'
import { useWindowReady } from '/rend/utils'

useWindowReady(ProgramWindow.setup)

const step = ref(0)

async function onChangeGameFolder(path: string) {
  Config.initialPath = path
  await Backup.save()
  await Archive.unpackMain()
  Helpers.reloadApp()
}
</script>

<style lang='scss'>
body {
  text-align: center;
  background: white;
}
</style>

<style lang='scss' scoped>
.steps {
  padding: 0 55px;
  margin-top: 10px;

  &-content {
    margin-top: 20px;
  }

  &-actions {
    position: absolute;
    width: 100%;
    bottom: 10px;
  }
}
</style>
