// src/renderer/modules/categories/components/Category.tsx
import { PureComponent } from 'react'
import { mainProcess, t } from 'scripts'
import { ListType } from 'modules/list/enums'

const { local } = window.provider
const { openList } = mainProcess

interface IProps {
    name: ListType
}

export class Category extends PureComponent<IProps> {
    private imgSrc: string

    constructor(props: IProps) {
        super(props)
        this.imgSrc = require(`images/category/${this.props.name}_category.png`)
    }

    render() {
        return (
            <div className='category' onClick={this.openList}>
                <img src={this.imgSrc} />
                <span className='category-name'>
                    {t[`${this.props.name.toUpperCase()}_CATEGORY_TITLE`]}
                </span>
            </div>
        )
    }

    private openList = () => {
        local.set('listType', this.props.name)
        openList()
    }
}

// src/scripts/modules/main/components/Category.vue
<template>
    <div class='category' @click='openList'>
        <img :src='imgSrc'>
        <span class='category-name'>
            {{ t[`${name.toUpperCase()}_CATEGORY_TITLE`] }}
        </span>
    </div>
</template>

<script lang='ts'>
import { defineComponent, toRefs } from 'vue'
import { t, mainProcess } from '../../../service'

export default defineComponent({
    props: {
        name: {
            type: String,
            required: true
        }
    },
    setup(props) {
        const { name } = toRefs(props)

        return {
            t,
            name
        }
    },
    methods: {
        openList() {
            local.set('listType', this.name)
            mainProcess.openList()
        }
    },
    computed: {
        imgSrc() {
            return require(`../../../../images/category/${this.name}_category.png`)
        }
    }
})
</script>

<style scoped>
.category {
    display: flex;
    height: 320px;
    width: 320px;
    position: relative;
    cursor: pointer;
}

.category:hover {
    filter: brightness(0.8);
}

.category:hover .category-name {
    color: yellow;
}

img {
    width: 100%;
    height: 100%;
    border-radius: 5px;
}

.category-name {
    width: 100%;
    color: white;
    background-color: black;
    position: absolute;
    top: 0;
    padding: 10px 0;
    text-align: center;
    text-transform: uppercase;
    border-top-right-radius: 5px;
    border-top-left-radius: 5px;
}
</style>
